package mgmtapi

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"regexp"
	"strings"
	"time"
)

// Route paths for the Stage 7.1 verbs. The trailing-resource
// segments (`/{id}/ingest`, `/{id}/ingest_delta`) are parsed
// by extractIngestPath; we DO NOT use net/http 1.22 method-
// based routing because the same handler also serves the
// 405 / 404 envelopes uniformly across every verb.
const (
	// RouteRepos is the prefix every Stage 7.1 route falls under.
	// Operators register a repo via POST /v1/repos and trigger
	// per-repo ingests via POST /v1/repos/{repo_id}/ingest[_delta].
	RouteRepos = "/v1/repos"

	// ingestSuffix is the trailing path segment that
	// distinguishes a full-ingest request from the register
	// surface (which has no suffix).
	ingestSuffix = "/ingest"

	// ingestDeltaSuffix is the trailing path segment for
	// `mgmt.ingest_delta`. Must be matched BEFORE
	// `ingestSuffix` since `/ingest` is a strict prefix of
	// `/ingest_delta` only after a literal `_`.
	ingestDeltaSuffix = "/ingest_delta"
)

// DefaultMaxBodyBytes caps the inbound JSON body so a
// malformed-but-authenticated request cannot exhaust process
// memory. 64 KiB is comfortably larger than any operator-shape
// request (the largest is mgmt.register with a URL, default
// branch, and a few flags — < 1 KiB realistically) and small
// enough that an O(1000) concurrent flood costs ~64 MiB at
// worst.
const DefaultMaxBodyBytes int64 = 64 << 10

// HMACSecretBytes is the entropy (in raw bytes) of the
// per-repo webhook HMAC secret generated by mgmt.register. The
// secret is hex-encoded for storage / transport, so the wire
// width is 2x this value. 32 bytes = 256 bits matches the
// HMAC-SHA256 key length recommended by RFC 2104; longer
// secrets do not add cryptographic strength for SHA-256 but
// cost more bytes everywhere.
const HMACSecretBytes = 32

// reUUID matches the RFC 4122 hex-and-hyphen shape. The DB
// `$1::uuid` cast is the canonical source of truth, but we
// pre-validate at the handler layer so a malformed path
// component returns 400 (operator error) rather than 500
// (the DB error would otherwise leak as an opaque
// `pq.Error`).
//
// Case-insensitive on hex digits per RFC 4122 §3.
var reUUID = regexp.MustCompile(
	`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

// Options bundles the optional knobs callers pass to
// [NewHandler]. Every field has a sensible default if zero-
// valued so the cmd binary can construct a working handler
// with just (db, verifier, resolver).
type Options struct {
	// Logger receives one structured record per request.
	// Defaults to slog.Default(). The handler NEVER logs the
	// webhook secret, the bearer token, the
	// `Authorization` header value, or the raw request
	// body.
	Logger *slog.Logger

	// MaxBodyBytes caps the request body the handler will
	// read. Zero means [DefaultMaxBodyBytes]; negative
	// disables the cap (NOT recommended in production).
	MaxBodyBytes int64

	// SecretGen overrides the function used to generate
	// per-repo webhook HMAC secrets. Defaults to a
	// crypto/rand-backed implementation that produces
	// [HMACSecretBytes] bytes of entropy hex-encoded.
	// Tests override to make the generated value
	// deterministic; production passes nil.
	SecretGen func() (string, error)

	// Clock is the time source the handler uses for
	// structured-log `received_at` fields. Database
	// timestamps use the server-side `now()` so a fixed
	// Go-side clock does NOT shift DB columns; tests that
	// need a frozen log timestamp inject one.
	Clock func() time.Time
}

// Handler is the Management API HTTP handler. Construct one
// per process via [NewHandler]; the same handler is safe for
// concurrent use across goroutines.
type Handler struct {
	db        *sql.DB
	verifier  TokenVerifier
	resolver  HeadResolver
	logger    *slog.Logger
	maxBody   int64
	secretGen func() (string, error)
	clock     func() time.Time

	// mux is the http.Handler the public ServeHTTP delegates
	// to after auth. Constructed in NewHandler so route
	// registration runs once.
	mux http.Handler
}

// NewHandler wires the Stage 7.1 routes onto `db`, `verifier`,
// and `resolver`. Panics on a nil *sql.DB, nil verifier, or
// nil resolver — none of those have a meaningful zero value
// in this context, and a process that calls NewHandler with
// any of them missing is a configuration error the operator
// should see at boot, not at the first request.
func NewHandler(db *sql.DB, verifier TokenVerifier, resolver HeadResolver, opts Options) *Handler {
	if db == nil {
		panic("mgmtapi: NewHandler: nil *sql.DB")
	}
	if verifier == nil {
		panic("mgmtapi: NewHandler: nil TokenVerifier")
	}
	if resolver == nil {
		panic("mgmtapi: NewHandler: nil HeadResolver")
	}
	logger := opts.Logger
	if logger == nil {
		logger = slog.Default()
	}
	maxBody := opts.MaxBodyBytes
	if maxBody == 0 {
		maxBody = DefaultMaxBodyBytes
	}
	clock := opts.Clock
	if clock == nil {
		clock = time.Now
	}
	secretGen := opts.SecretGen
	if secretGen == nil {
		secretGen = defaultSecretGen
	}
	h := &Handler{
		db:        db,
		verifier:  verifier,
		resolver:  resolver,
		logger:    logger,
		maxBody:   maxBody,
		secretGen: secretGen,
		clock:     clock,
	}
	// Build the inner mux. The outer ServeHTTP runs auth
	// FIRST so we wrap this once. Method gating happens
	// inside each verb so we can emit a uniform JSON 405
	// envelope on the wrong verb.
	inner := http.HandlerFunc(h.route)
	h.mux = authMiddleware(verifier, logger, inner)
	return h
}

// ServeHTTP is the public entry point. Delegates to the auth-
// gated mux; the auth layer 401-rejects before any request
// body is read.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.mux.ServeHTTP(w, r)
}

// route dispatches an authenticated request to the right verb
// handler. Method gating + path parsing live here so every
// verb shares the same 404 / 405 envelopes.
func (h *Handler) route(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		w.Header().Set("Allow", http.MethodPost)
		writeJSONError(w, http.StatusMethodNotAllowed, "method_not_allowed",
			fmt.Sprintf("method %s not allowed; use POST", r.Method))
		return
	}

	// /v1/repos               -> register
	// /v1/repos/{id}/ingest   -> ingest
	// /v1/repos/{id}/ingest_delta -> ingest_delta
	switch {
	case r.URL.Path == RouteRepos, r.URL.Path == RouteRepos+"/":
		h.handleRegister(w, r)
		return
	case strings.HasPrefix(r.URL.Path, RouteRepos+"/"):
		repoID, suffix, ok := extractIngestPath(r.URL.Path)
		if !ok {
			writeJSONError(w, http.StatusNotFound, "not_found",
				"unknown management API route")
			return
		}
		switch suffix {
		case ingestSuffix:
			h.handleIngest(w, r, repoID)
		case ingestDeltaSuffix:
			h.handleIngestDelta(w, r, repoID)
		default:
			writeJSONError(w, http.StatusNotFound, "not_found",
				"unknown management API route")
		}
		return
	default:
		writeJSONError(w, http.StatusNotFound, "not_found",
			"unknown management API route")
	}
}

// extractIngestPath parses `/v1/repos/{repo_id}/ingest` or
// `/v1/repos/{repo_id}/ingest_delta`. Returns the raw repo_id
// string and the suffix (`/ingest` or `/ingest_delta`). The
// repo_id is NOT validated as a UUID here — that's the verb
// handler's job so 400 / 404 attribution stays clean.
//
// Returns ok=false for any path that does not match either
// shape exactly.
func extractIngestPath(path string) (repoID, suffix string, ok bool) {
	rest := strings.TrimPrefix(path, RouteRepos+"/")
	// Match the longest suffix first: `/ingest_delta` is a
	// strict superset of `/ingest`.
	for _, s := range []string{ingestDeltaSuffix, ingestSuffix} {
		if strings.HasSuffix(rest, s) {
			id := strings.TrimSuffix(rest, s)
			// Reject extra path segments like
			// `/v1/repos/{id}/foo/ingest`. The repo_id
			// segment MUST be the only thing before
			// the suffix.
			if id == "" || strings.Contains(id, "/") {
				return "", "", false
			}
			return id, s, true
		}
	}
	return "", "", false
}

// -----------------------------------------------------------
// mgmt.register
// -----------------------------------------------------------

// RegisterRequest is the wire shape of POST /v1/repos. Field
// names use lower_snake_case to match the rest of the
// service's JSON style.
//
// Architecture.md §6.2.1 pins the verb signature as
// `mgmt.register(repo_url, default_branch)` — no SHA in the
// request. The handler resolves HEAD via the injected
// [HeadResolver] so the schema-level `current_head_sha NOT
// NULL` invariant holds without exposing the resolution
// machinery on the wire.
type RegisterRequest struct {
	RepoURL       string `json:"repo_url"`
	DefaultBranch string `json:"default_branch"`
}

// RegisterResponse is the wire shape of a successful POST
// /v1/repos. `WebhookSecret` is set only on first
// registration of a given URL — re-registering the same URL
// returns a body WITHOUT `webhook_secret` per the e2e §1
// idempotent-re-register contract and the Stage 7.1 "secret
// revealed exactly once" invariant.
type RegisterResponse struct {
	RepoID         string `json:"repo_id"`
	DefaultBranch  string `json:"default_branch"`
	CurrentHeadSHA string `json:"current_head_sha"`
	// Status is `registered` on a brand-new repo and
	// `exists` when the operator re-registered an existing
	// URL. Lets the operator UI distinguish the two cases
	// without inspecting the absence of `webhook_secret`.
	Status string `json:"status"`
	// WebhookSecret is the per-repo HMAC pre-shared secret
	// returned ONLY on first registration. Omitted from the
	// JSON output when empty (`omitempty`), so a re-register
	// reply never even mentions the field.
	WebhookSecret string `json:"webhook_secret,omitempty"`
	// IngestJobID is the freshly-enqueued full-ingest job's
	// id. Set only on first registration (the operator can
	// poll its state via mgmt.read.repos / mgmt.read.commits
	// once those land in Stage 7.5).
	IngestJobID string `json:"ingest_job_id,omitempty"`
}

func (h *Handler) handleRegister(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	var req RegisterRequest
	if !h.decodeJSONBody(w, r, &req) {
		return
	}

	// --- input validation ---
	repoURL, err := normalizeRepoURL(req.RepoURL)
	if err != nil {
		writeJSONError(w, http.StatusBadRequest, "invalid_request", err.Error())
		return
	}
	branch, err := normalizeRef(req.DefaultBranch)
	if err != nil {
		writeJSONError(w, http.StatusBadRequest, "invalid_request", err.Error())
		return
	}

	// --- resolve HEAD before doing any DB work ---
	//
	// Doing this BEFORE the transaction means a resolver
	// outage cannot leave a half-written `repo` row or an
	// orphan `repo_webhook_secret`. The transaction's
	// ON CONFLICT (url) DO NOTHING handles concurrent
	// register races at the DB level.
	headSHA, err := h.resolver.Resolve(ctx, repoURL, branch)
	if err != nil {
		h.handleResolverError(w, r, "register", repoURL, err)
		return
	}
	if !IsHexGitSHA(headSHA) {
		// Defence-in-depth: a resolver that returns
		// something that isn't a SHA is a contract violation;
		// we treat it as an upstream failure (502) so the
		// operator can retry and the structured log makes
		// the offence visible.
		h.logger.Error("mgmtapi.register.resolver_bad_shape",
			slog.String("op", "register"),
			slog.String("repo_url", repoURL),
			slog.String("returned", headSHA),
		)
		writeJSONError(w, http.StatusBadGateway, "head_resolver_unavailable",
			"head resolver returned a non-SHA value")
		return
	}

	// --- generate the secret BEFORE opening the tx ---
	//
	// A crypto/rand read could in principle fail (it never
	// does on a healthy kernel, but the API permits it).
	// Failing before the tx means we have no partial state
	// to roll back.
	webhookSecret, err := h.secretGen()
	if err != nil {
		h.logger.Error("mgmtapi.register.secret_gen_failed",
			slog.String("op", "register"),
			slog.String("error", err.Error()),
		)
		writeJSONError(w, http.StatusInternalServerError, "internal_error",
			"failed to generate webhook secret")
		return
	}

	// --- atomic write path ---
	resp, err := h.executeRegister(ctx, repoURL, branch, headSHA, webhookSecret)
	if err != nil {
		h.logger.Error("mgmtapi.register.db_failed",
			slog.String("op", "register"),
			slog.String("repo_url", repoURL),
			slog.String("error", err.Error()),
		)
		writeJSONError(w, http.StatusInternalServerError, "internal_error",
			"internal error")
		return
	}

	status := http.StatusOK
	if resp.Status == "registered" {
		status = http.StatusCreated
	}
	subject, _ := SubjectFromContext(ctx)
	h.logger.Info("mgmtapi.register.ok",
		slog.String("op", "register"),
		slog.String("repo_id", resp.RepoID),
		slog.String("status", resp.Status),
		slog.Bool("returned_secret", resp.WebhookSecret != ""),
		slog.String("subject", subject),
		slog.Time("at", h.clock()),
	)
	writeJSONResponse(w, status, resp)
}

// executeRegister runs the register transaction. Separated
// from handleRegister so the SQL shape is testable without
// going through the HTTP layer.
func (h *Handler) executeRegister(ctx context.Context, repoURL, branch, headSHA, webhookSecret string) (RegisterResponse, error) {
	tx, err := h.db.BeginTx(ctx, nil)
	if err != nil {
		return RegisterResponse{}, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck // commit path makes rollback a no-op; best-effort cleanup otherwise

	// Step 1: INSERT INTO repo with ON CONFLICT (url) DO
	// NOTHING — the migration 0002 UNIQUE INDEX on
	// repo.url makes this idempotent. RETURNING repo_id::text
	// returns a row only on a NEW insertion.
	const insertRepo = `
		INSERT INTO repo (url, default_branch, current_head_sha)
		VALUES ($1, $2, $3)
		ON CONFLICT (url) DO NOTHING
		RETURNING repo_id::text
	`
	var repoID string
	err = tx.QueryRowContext(ctx, insertRepo, repoURL, branch, headSHA).Scan(&repoID)
	if errors.Is(err, sql.ErrNoRows) {
		// Repo already exists. Fetch its id and short-circuit:
		// the secret stays unrevealed, no new RepoEvent,
		// no new ingest_jobs row (per the e2e §1 idempotent
		// re-register scenario).
		const selectExisting = `
			SELECT repo_id::text, default_branch, current_head_sha
			FROM repo
			WHERE url = $1
		`
		var existingBranch, existingHead string
		if err := tx.QueryRowContext(ctx, selectExisting, repoURL).
			Scan(&repoID, &existingBranch, &existingHead); err != nil {
			return RegisterResponse{}, fmt.Errorf("select existing repo: %w", err)
		}
		if err := tx.Commit(); err != nil {
			return RegisterResponse{}, fmt.Errorf("commit tx (existing): %w", err)
		}
		return RegisterResponse{
			RepoID:         repoID,
			DefaultBranch:  existingBranch,
			CurrentHeadSHA: existingHead,
			Status:         "exists",
		}, nil
	}
	if err != nil {
		return RegisterResponse{}, fmt.Errorf("insert repo: %w", err)
	}

	// Step 2: stash the webhook secret. Migration 0018 makes
	// `repo_id` the PK, so this also rejects a duplicate
	// secret-write if anybody ever bypasses the
	// `ON CONFLICT` path above.
	const insertSecret = `
		INSERT INTO repo_webhook_secret (repo_id, webhook_secret)
		VALUES ($1::uuid, $2)
	`
	if _, err := tx.ExecContext(ctx, insertSecret, repoID, webhookSecret); err != nil {
		return RegisterResponse{}, fmt.Errorf("insert repo_webhook_secret: %w", err)
	}

	// Step 3: audit event (kind='register'). architecture.md
	// §5.6 line 644 pins the closed set of kinds; ENUM
	// migration 0001 enforces it at the DB.
	const insertEvent = `
		INSERT INTO repo_event (repo_id, kind, from_sha, to_sha)
		VALUES ($1::uuid, 'register'::repo_event_kind, NULL, $2)
	`
	if _, err := tx.ExecContext(ctx, insertEvent, repoID, headSHA); err != nil {
		return RegisterResponse{}, fmt.Errorf("insert repo_event: %w", err)
	}

	// Step 4: enqueue the full-ingest job. ON CONFLICT DO
	// NOTHING handles the (vanishingly unlikely) race where
	// a parallel register lost the repo INSERT race but won
	// the job INSERT race — exit cleanly either way.
	const insertJob = `
		INSERT INTO ingest_jobs (repo_id, mode, from_sha, to_sha)
		VALUES ($1::uuid, 'full'::ingest_mode, NULL, $2)
		ON CONFLICT (repo_id, mode, (COALESCE(from_sha, '')), to_sha) DO NOTHING
		RETURNING job_id::text
	`
	var jobID string
	err = tx.QueryRowContext(ctx, insertJob, repoID, headSHA).Scan(&jobID)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return RegisterResponse{}, fmt.Errorf("insert ingest_jobs: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return RegisterResponse{}, fmt.Errorf("commit tx: %w", err)
	}
	return RegisterResponse{
		RepoID:         repoID,
		DefaultBranch:  branch,
		CurrentHeadSHA: headSHA,
		Status:         "registered",
		WebhookSecret:  webhookSecret,
		IngestJobID:    jobID,
	}, nil
}

// -----------------------------------------------------------
// mgmt.ingest
// -----------------------------------------------------------

// IngestRequest is the wire shape of POST /v1/repos/{id}/ingest.
// `SHA` is optional; if empty, the handler resolves HEAD via
// the [HeadResolver] (the architecture pins the verb signature
// as `mgmt.ingest(repo_id, sha?)`).
type IngestRequest struct {
	SHA string `json:"sha,omitempty"`
}

// IngestResponse is the wire shape of a successful POST
// /v1/repos/{id}/ingest. The endpoint is asynchronous —
// `status` reflects the freshly-enqueued / pre-existing job
// state, and the caller polls `mgmt.read.repos` for ingest
// progress (Stage 7.5).
type IngestResponse struct {
	IngestJobID string `json:"ingest_job_id"`
	JobState    string `json:"job_state"`
	Mode        string `json:"mode"`
	ToSHA       string `json:"to_sha"`
	// Deduped is true when the job already existed; useful
	// to operators triaging "did my retry land or did I
	// double-trigger?" alerts.
	Deduped bool `json:"deduped"`
}

func (h *Handler) handleIngest(w http.ResponseWriter, r *http.Request, rawRepoID string) {
	ctx := r.Context()

	if !reUUID.MatchString(rawRepoID) {
		writeJSONError(w, http.StatusBadRequest, "invalid_repo_id",
			"repo_id path segment is not a valid UUID")
		return
	}

	var req IngestRequest
	if !h.decodeJSONBody(w, r, &req) {
		return
	}

	// Validate the supplied SHA shape BEFORE any DB read. An
	// operator-supplied bad SHA should always be 400, never
	// masked by a transient DB outage as a 500. The default-
	// HEAD case (empty SHA) requires loadRepo + resolver
	// downstream, but a non-empty operator SHA short-circuits
	// here.
	sha := strings.TrimSpace(req.SHA)
	if sha != "" && !IsHexGitSHA(sha) {
		writeJSONError(w, http.StatusBadRequest, "invalid_sha",
			"sha must be a 40- or 64-char lower-case hex git SHA")
		return
	}

	// Look up the repo so we can default sha against a live
	// HEAD resolve (when no SHA was supplied) AND return 404
	// cleanly when the id is well-formed but unknown.
	repoURL, branch, _, err := h.loadRepo(ctx, rawRepoID)
	if errors.Is(err, sql.ErrNoRows) {
		writeJSONError(w, http.StatusNotFound, "repo_not_found",
			"no repo with the supplied repo_id")
		return
	}
	if err != nil {
		h.logger.Error("mgmtapi.ingest.load_repo_failed",
			slog.String("op", "ingest"),
			slog.String("repo_id", rawRepoID),
			slog.String("error", err.Error()),
		)
		writeJSONError(w, http.StatusInternalServerError, "internal_error", "internal error")
		return
	}

	if sha == "" {
		// "Default HEAD" semantics: ask the live resolver.
		// We do NOT silently fall back to the cached
		// `repo.current_head_sha` — Stage 7.1 write verbs
		// have no degraded-mode contract, and quietly
		// enqueueing the cached SHA would let a stale value
		// hide a resolver outage from the operator. Any
		// resolver failure is surfaced explicitly: 400 on
		// "ref not found", 502 on transient outage.
		resolved, rerr := h.resolver.Resolve(ctx, repoURL, branch)
		if rerr != nil {
			h.handleResolverError(w, r, "ingest", repoURL, rerr)
			return
		}
		if !IsHexGitSHA(resolved) {
			// A resolver that returned a non-hex value is
			// itself a bug / outage. Treat as 502 so the
			// operator can retry / page the team owning
			// the resolver.
			h.logger.Error("mgmtapi.ingest.resolver_returned_non_sha",
				slog.String("op", "ingest"),
				slog.String("repo_id", rawRepoID),
				slog.String("resolved", resolved),
			)
			writeJSONError(w, http.StatusBadGateway, "head_resolver_unavailable",
				"head resolver returned a non-SHA value")
			return
		}
		sha = resolved
	}

	resp, err := h.executeIngest(ctx, rawRepoID, sha)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) || isForeignKeyViolation(err) {
			// Repo was deleted between loadRepo and the
			// INSERT (unlikely but possible). Surface 404
			// instead of 500.
			writeJSONError(w, http.StatusNotFound, "repo_not_found",
				"no repo with the supplied repo_id")
			return
		}
		h.logger.Error("mgmtapi.ingest.db_failed",
			slog.String("op", "ingest"),
			slog.String("repo_id", rawRepoID),
			slog.String("to_sha", sha),
			slog.String("error", err.Error()),
		)
		writeJSONError(w, http.StatusInternalServerError, "internal_error", "internal error")
		return
	}

	subject, _ := SubjectFromContext(ctx)
	h.logger.Info("mgmtapi.ingest.ok",
		slog.String("op", "ingest"),
		slog.String("repo_id", rawRepoID),
		slog.String("ingest_job_id", resp.IngestJobID),
		slog.String("job_state", resp.JobState),
		slog.String("to_sha", sha),
		slog.Bool("deduped", resp.Deduped),
		slog.String("subject", subject),
		slog.Time("at", h.clock()),
	)
	writeJSONResponse(w, http.StatusAccepted, resp)
}

func (h *Handler) executeIngest(ctx context.Context, repoID, toSHA string) (IngestResponse, error) {
	tx, err := h.db.BeginTx(ctx, nil)
	if err != nil {
		return IngestResponse{}, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	// Try to enqueue. ON CONFLICT DO NOTHING returns no row
	// when the same (repo_id, mode='full', '', to_sha)
	// tuple already exists; we then SELECT the existing
	// row's id and skip the RepoEvent write (so a retry
	// does not pollute the audit log).
	const insertJob = `
		INSERT INTO ingest_jobs (repo_id, mode, from_sha, to_sha)
		VALUES ($1::uuid, 'full'::ingest_mode, NULL, $2)
		ON CONFLICT (repo_id, mode, (COALESCE(from_sha, '')), to_sha) DO NOTHING
		RETURNING job_id::text, status::text
	`
	var jobID, jobState string
	err = tx.QueryRowContext(ctx, insertJob, repoID, toSHA).Scan(&jobID, &jobState)
	switch {
	case err == nil:
		// New row; write the matching RepoEvent.
		const insertEvent = `
			INSERT INTO repo_event (repo_id, kind, from_sha, to_sha)
			VALUES ($1::uuid, 'manual'::repo_event_kind, NULL, $2)
		`
		if _, err := tx.ExecContext(ctx, insertEvent, repoID, toSHA); err != nil {
			return IngestResponse{}, fmt.Errorf("insert repo_event: %w", err)
		}
		if err := tx.Commit(); err != nil {
			return IngestResponse{}, fmt.Errorf("commit tx: %w", err)
		}
		return IngestResponse{
			IngestJobID: jobID, JobState: jobState, Mode: "full", ToSHA: toSHA, Deduped: false,
		}, nil
	case errors.Is(err, sql.ErrNoRows):
		// Existing job. Look it up and DO NOT write a new
		// RepoEvent — the audit log already has the
		// first-call's event row.
		const selectExisting = `
			SELECT job_id::text, status::text
			FROM ingest_jobs
			WHERE repo_id = $1::uuid
			  AND mode = 'full'::ingest_mode
			  AND COALESCE(from_sha, '') = ''
			  AND to_sha = $2
		`
		if err := tx.QueryRowContext(ctx, selectExisting, repoID, toSHA).
			Scan(&jobID, &jobState); err != nil {
			return IngestResponse{}, fmt.Errorf("select existing ingest_jobs: %w", err)
		}
		if err := tx.Commit(); err != nil {
			return IngestResponse{}, fmt.Errorf("commit tx (existing): %w", err)
		}
		return IngestResponse{
			IngestJobID: jobID, JobState: jobState, Mode: "full", ToSHA: toSHA, Deduped: true,
		}, nil
	default:
		return IngestResponse{}, fmt.Errorf("insert ingest_jobs: %w", err)
	}
}

// -----------------------------------------------------------
// mgmt.ingest_delta
// -----------------------------------------------------------

// IngestDeltaRequest is the wire shape of POST
// /v1/repos/{id}/ingest_delta. Both SHAs are REQUIRED — the
// architecture verb signature is `mgmt.ingest_delta(repo_id,
// from_sha, to_sha)`. A delta with no from-SHA is by
// definition a full ingest and should go through mgmt.ingest.
type IngestDeltaRequest struct {
	FromSHA string `json:"from_sha"`
	ToSHA   string `json:"to_sha"`
}

// IngestDeltaResponse is the wire shape of a successful POST
// /v1/repos/{id}/ingest_delta. The `Deduped` flag is the
// public signal of the idempotency contract — operators
// retrying a delta-ingest call see `deduped=true` and the
// same `ingest_job_id` they got the first time.
type IngestDeltaResponse struct {
	IngestJobID string `json:"ingest_job_id"`
	JobState    string `json:"job_state"`
	Mode        string `json:"mode"`
	FromSHA     string `json:"from_sha"`
	ToSHA       string `json:"to_sha"`
	Deduped     bool   `json:"deduped"`
}

func (h *Handler) handleIngestDelta(w http.ResponseWriter, r *http.Request, rawRepoID string) {
	ctx := r.Context()

	if !reUUID.MatchString(rawRepoID) {
		writeJSONError(w, http.StatusBadRequest, "invalid_repo_id",
			"repo_id path segment is not a valid UUID")
		return
	}

	var req IngestDeltaRequest
	if !h.decodeJSONBody(w, r, &req) {
		return
	}

	from := strings.TrimSpace(req.FromSHA)
	to := strings.TrimSpace(req.ToSHA)
	if from == "" {
		writeJSONError(w, http.StatusBadRequest, "invalid_request",
			"from_sha: required")
		return
	}
	if to == "" {
		writeJSONError(w, http.StatusBadRequest, "invalid_request",
			"to_sha: required")
		return
	}
	if !IsHexGitSHA(from) {
		writeJSONError(w, http.StatusBadRequest, "invalid_sha",
			"from_sha must be a 40- or 64-char lower-case hex git SHA")
		return
	}
	if !IsHexGitSHA(to) {
		writeJSONError(w, http.StatusBadRequest, "invalid_sha",
			"to_sha must be a 40- or 64-char lower-case hex git SHA")
		return
	}
	if from == to {
		writeJSONError(w, http.StatusBadRequest, "invalid_request",
			"from_sha and to_sha must differ")
		return
	}

	resp, err := h.executeIngestDelta(ctx, rawRepoID, from, to)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) || isForeignKeyViolation(err) {
			writeJSONError(w, http.StatusNotFound, "repo_not_found",
				"no repo with the supplied repo_id")
			return
		}
		h.logger.Error("mgmtapi.ingest_delta.db_failed",
			slog.String("op", "ingest_delta"),
			slog.String("repo_id", rawRepoID),
			slog.String("from_sha", from),
			slog.String("to_sha", to),
			slog.String("error", err.Error()),
		)
		writeJSONError(w, http.StatusInternalServerError, "internal_error", "internal error")
		return
	}

	subject, _ := SubjectFromContext(ctx)
	h.logger.Info("mgmtapi.ingest_delta.ok",
		slog.String("op", "ingest_delta"),
		slog.String("repo_id", rawRepoID),
		slog.String("ingest_job_id", resp.IngestJobID),
		slog.String("job_state", resp.JobState),
		slog.String("from_sha", from),
		slog.String("to_sha", to),
		slog.Bool("deduped", resp.Deduped),
		slog.String("subject", subject),
		slog.Time("at", h.clock()),
	)
	writeJSONResponse(w, http.StatusAccepted, resp)
}

func (h *Handler) executeIngestDelta(ctx context.Context, repoID, fromSHA, toSHA string) (IngestDeltaResponse, error) {
	tx, err := h.db.BeginTx(ctx, nil)
	if err != nil {
		return IngestDeltaResponse{}, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	// ON CONFLICT (repo_id, mode, (COALESCE(from_sha, '')),
	// to_sha) DO NOTHING is the canonical idempotent
	// delta-enqueue. RETURNING is empty on conflict; that's
	// the signal we use to skip the RepoEvent insert and
	// look up the existing job.
	const insertJob = `
		INSERT INTO ingest_jobs (repo_id, mode, from_sha, to_sha)
		VALUES ($1::uuid, 'delta'::ingest_mode, $2, $3)
		ON CONFLICT (repo_id, mode, (COALESCE(from_sha, '')), to_sha) DO NOTHING
		RETURNING job_id::text, status::text
	`
	var jobID, jobState string
	err = tx.QueryRowContext(ctx, insertJob, repoID, fromSHA, toSHA).Scan(&jobID, &jobState)
	switch {
	case err == nil:
		const insertEvent = `
			INSERT INTO repo_event (repo_id, kind, from_sha, to_sha)
			VALUES ($1::uuid, 'manual'::repo_event_kind, $2, $3)
		`
		if _, err := tx.ExecContext(ctx, insertEvent, repoID, fromSHA, toSHA); err != nil {
			return IngestDeltaResponse{}, fmt.Errorf("insert repo_event: %w", err)
		}
		if err := tx.Commit(); err != nil {
			return IngestDeltaResponse{}, fmt.Errorf("commit tx: %w", err)
		}
		return IngestDeltaResponse{
			IngestJobID: jobID, JobState: jobState, Mode: "delta",
			FromSHA: fromSHA, ToSHA: toSHA, Deduped: false,
		}, nil
	case errors.Is(err, sql.ErrNoRows):
		const selectExisting = `
			SELECT job_id::text, status::text
			FROM ingest_jobs
			WHERE repo_id = $1::uuid
			  AND mode = 'delta'::ingest_mode
			  AND COALESCE(from_sha, '') = $2
			  AND to_sha = $3
		`
		if err := tx.QueryRowContext(ctx, selectExisting, repoID, fromSHA, toSHA).
			Scan(&jobID, &jobState); err != nil {
			return IngestDeltaResponse{}, fmt.Errorf("select existing ingest_jobs: %w", err)
		}
		if err := tx.Commit(); err != nil {
			return IngestDeltaResponse{}, fmt.Errorf("commit tx (existing): %w", err)
		}
		return IngestDeltaResponse{
			IngestJobID: jobID, JobState: jobState, Mode: "delta",
			FromSHA: fromSHA, ToSHA: toSHA, Deduped: true,
		}, nil
	default:
		return IngestDeltaResponse{}, fmt.Errorf("insert ingest_jobs: %w", err)
	}
}

// -----------------------------------------------------------
// Shared helpers
// -----------------------------------------------------------

// loadRepo fetches the columns the ingest verbs need to
// resolve a default SHA against the cached HEAD. Returns
// [sql.ErrNoRows] when the id is well-formed but not found.
//
// Also classifies a PostgreSQL `invalid input syntax for
// type uuid` error as `sql.ErrNoRows` so a future code path
// that hits this helper with an unvalidated id still falls
// onto the 404 branch instead of leaking a 500.
func (h *Handler) loadRepo(ctx context.Context, repoID string) (repoURL, defaultBranch, currentHead string, err error) {
	const q = `
		SELECT url, default_branch, current_head_sha
		FROM repo
		WHERE repo_id = $1::uuid
	`
	err = h.db.QueryRowContext(ctx, q, repoID).Scan(&repoURL, &defaultBranch, &currentHead)
	if err != nil && isInvalidUUIDError(err) {
		return "", "", "", sql.ErrNoRows
	}
	return repoURL, defaultBranch, currentHead, err
}

// decodeJSONBody decodes the request body into `dst` and
// returns false on any error after writing the appropriate
// 4xx response. Imposes the configured body cap so a
// pathological body cannot exhaust memory.
//
// JSON shape rules:
//
//   - The body must be a single JSON object — top-level
//     arrays, numbers, or nulls are rejected by `json.Decode`
//     into a struct.
//   - Unknown fields are ALLOWED (forward-compat with
//     newer clients). Tightening this is a future change.
//   - Empty body is accepted iff `dst` has no required
//     fields — required-field validation is the verb
//     handler's job.
func (h *Handler) decodeJSONBody(w http.ResponseWriter, r *http.Request, dst any) bool {
	if h.maxBody > 0 {
		r.Body = http.MaxBytesReader(w, r.Body, h.maxBody)
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		var mxErr *http.MaxBytesError
		if errors.As(err, &mxErr) {
			writeJSONError(w, http.StatusRequestEntityTooLarge,
				"body_too_large",
				fmt.Sprintf("request body exceeds %d bytes", h.maxBody))
			return false
		}
		writeJSONError(w, http.StatusBadRequest, "bad_request",
			"failed to read request body")
		return false
	}
	if len(body) == 0 {
		// An empty body decodes to the zero value of `dst`;
		// callers run required-field validation explicitly.
		return true
	}
	if err := json.Unmarshal(body, dst); err != nil {
		writeJSONError(w, http.StatusBadRequest, "invalid_json",
			"request body is not valid JSON")
		return false
	}
	return true
}

// normalizeRepoURL validates and canonicalises an operator-
// supplied repo URL. The schema treats `repo.url` as opaque
// text, but the UNIQUE INDEX on it means inconsistent
// trailing slashes / scheme casing would defeat
// idempotency. We:
//
//   - Trim leading / trailing whitespace.
//   - Require a non-empty value.
//   - Require a parseable URL with a scheme (http / https /
//     ssh / git+ssh) and a host. A bare path like `acme/svc`
//     is rejected so the audit log never carries an
//     unresolvable identifier.
//
// The handler does NOT touch URL case (some git hosts treat
// the path as case-sensitive) and does NOT strip trailing
// slashes or `.git` suffixes — those are part of the
// canonical URL the operator chose.
func normalizeRepoURL(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", errors.New("repo_url: required")
	}
	u, err := url.Parse(raw)
	if err != nil {
		return "", fmt.Errorf("repo_url: %v", err)
	}
	if u.Scheme == "" {
		return "", errors.New("repo_url: missing scheme (use https://, ssh://, or git@host:path)")
	}
	// SCP-style URLs (`git@host:path`) get parsed as a
	// path-only URL with Scheme=="" — we already reject
	// those above. A real git host URL has either a Host
	// (https://) or an Opaque path (ssh://user@host/path).
	if u.Host == "" && u.Opaque == "" {
		return "", errors.New("repo_url: missing host")
	}
	return raw, nil
}

// defaultSecretGen produces a fresh, hex-encoded
// [HMACSecretBytes]-byte random secret. Used by the
// production composition root and as the default when
// Options.SecretGen is nil.
//
// crypto/rand.Read returns an error only under exceptional
// host conditions (the OS RNG device is unreachable); the
// handler treats that as a 500 internal error so the
// operator can retry. Note: we deliberately do NOT silently
// fall back to math/rand — a non-cryptographic secret would
// be worse than no secret at all because callers downstream
// trust the value to be HMAC-keyworthy.
func defaultSecretGen() (string, error) {
	buf := make([]byte, HMACSecretBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("crypto/rand: %w", err)
	}
	return hex.EncodeToString(buf), nil
}

// handleResolverError maps a HeadResolver-returned error onto
// the matching response. Centralised so the register and
// ingest verbs apply identical classification rules.
func (h *Handler) handleResolverError(w http.ResponseWriter, r *http.Request, op, repoURL string, err error) {
	switch {
	case errors.Is(err, ErrHeadResolverUnknownRef):
		writeJSONError(w, http.StatusBadRequest, "unknown_ref",
			"default branch was not found on the remote")
	case errors.Is(err, ErrHeadResolverUnavailable), err == nil:
		// `err == nil` here is a defence-in-depth fallback
		// — if a caller routes a non-error path into this
		// function we still produce a 502 so the operator
		// has a sensible signal.
		writeJSONError(w, http.StatusBadGateway, "head_resolver_unavailable",
			"head resolver is unavailable; retry shortly")
	default:
		writeJSONError(w, http.StatusBadGateway, "head_resolver_unavailable",
			"head resolver is unavailable; retry shortly")
	}
	h.logger.Warn("mgmtapi."+op+".resolver_failed",
		slog.String("op", op),
		slog.String("repo_url", repoURL),
		slog.String("path", r.URL.Path),
		slog.String("error", errToString(err)),
	)
}

// errToString safely renders an error for structured logging.
// Returns the literal `"<nil>"` for a nil error so a stray
// log line that includes the error attribute regardless of
// nilness still produces a parseable record.
func errToString(err error) string {
	if err == nil {
		return "<nil>"
	}
	return err.Error()
}

// isInvalidUUIDError matches the PostgreSQL SQLSTATE 22P02
// (`invalid_text_representation`) error that the `$1::uuid`
// cast produces when the input is not a valid UUID. Copied
// in spirit from internal/webhookreceiver.isInvalidUUIDError;
// kept local to avoid a cross-package internal dependency.
func isInvalidUUIDError(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "invalid input syntax for type uuid")
}

// isForeignKeyViolation matches PostgreSQL SQLSTATE 23503
// (`foreign_key_violation`). Used to map a delete-during-
// register race onto a 404 instead of a 500. We look at
// the error message text rather than pull in `lib/pq`'s
// typed error struct so the helper works with any
// pq-compatible driver (lib/pq, pgx via stdlib).
func isForeignKeyViolation(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	// pq formats: `pq: insert or update on table "repo_event"
	// violates foreign key constraint ...`. pgx/stdlib:
	// similar shape with the `foreign key constraint`
	// substring.
	return strings.Contains(msg, "foreign key constraint") ||
		strings.Contains(msg, "sqlstate 23503")
}

// -----------------------------------------------------------
// JSON response envelopes
// -----------------------------------------------------------

// ErrorEnvelope is the shape every non-2xx response carries.
// Keeping a single shape across all verbs lets the operator
// UI render errors uniformly.
//
// `Code` is a stable lower_snake_case enum the UI / clients
// can dispatch on (e.g. `invalid_request`, `repo_not_found`,
// `head_resolver_unavailable`). `Message` is operator-facing
// human-readable text — short, never leaks driver / SQL
// detail, safe to render.
type ErrorEnvelope struct {
	Error   bool   `json:"error"`
	Code    string `json:"code"`
	Message string `json:"message"`
	// Degraded mirrors the §6.3 degraded-mode contract
	// shape for read paths; included on every response so
	// downstream clients can rely on the field always being
	// present even when the write path itself is fully
	// healthy. Stage 7.1 always returns `false` here —
	// write verbs do not have a degraded mode in the
	// architecture contract.
	Degraded bool `json:"degraded"`
}

// DegradedEnvelope wraps a successful response with the
// `degraded` / `degraded_reason` fields that architecture.md
// §6.3 promises for every mgmt.* verb. Stage 7.1 write
// verbs never serve a degraded response, but the helper is
// here so the downstream read verbs (Stage 7.5) can share
// the same envelope shape without a follow-up refactor.
//
// Encoding rule: callers `json.Marshal` the payload struct,
// then this helper merges the degraded fields with the
// payload at the top level. Implemented via a generic
// wrapper struct rather than `map[string]any` so a payload
// type with non-string fields round-trips cleanly.
type DegradedEnvelope[T any] struct {
	// Embedded so the JSON-marshaled top-level field set is
	// the payload's fields PLUS the degraded fields.
	Payload T
	// Degraded is true iff the verb fell back to a
	// degraded surface (cached snapshot, stale read, etc).
	// For Stage 7.1 write verbs this stays false.
	Degraded bool `json:"degraded"`
	// DegradedReason is a short operator-facing string
	// explaining the fallback. Omitted on non-degraded
	// responses (`omitempty`).
	DegradedReason string `json:"degraded_reason,omitempty"`
}

// MarshalJSON implements [json.Marshaler] for
// [DegradedEnvelope]. It produces a flat JSON object with the
// payload's fields merged at the top level alongside
// `degraded` / `degraded_reason`.
//
// The helper is used by Stage 7.5 read verbs once they land;
// Stage 7.1 write verbs do not invoke it in the happy path
// (the responses they produce are pure success shapes). The
// type and method exist now so the §6.3 envelope contract is
// satisfied without a future, surprise-prone refactor.
func (d DegradedEnvelope[T]) MarshalJSON() ([]byte, error) {
	// Marshal the payload first; if the payload type is
	// itself a struct, this produces a JSON object we can
	// peel the outer braces off of and re-emit with the
	// extra fields appended.
	pb, err := json.Marshal(d.Payload)
	if err != nil {
		return nil, fmt.Errorf("DegradedEnvelope: payload marshal: %w", err)
	}
	if len(pb) < 2 || pb[0] != '{' || pb[len(pb)-1] != '}' {
		// Non-object payload (number, string, array, null,
		// boolean). The §6.3 envelope is only well-defined
		// for object responses; the v1 surface uses object
		// payloads exclusively.
		return nil, fmt.Errorf("DegradedEnvelope: payload is not a JSON object: %s", pb)
	}
	extra := map[string]any{"degraded": d.Degraded}
	if d.DegradedReason != "" {
		extra["degraded_reason"] = d.DegradedReason
	}
	xb, err := json.Marshal(extra)
	if err != nil {
		return nil, fmt.Errorf("DegradedEnvelope: extra marshal: %w", err)
	}
	if len(xb) == 2 { // "{}"
		return pb, nil
	}
	// Merge: drop the trailing `}` from `pb`, drop the
	// leading `{` from `xb`, glue with a comma.
	out := make([]byte, 0, len(pb)+len(xb)+1)
	out = append(out, pb[:len(pb)-1]...)
	if len(pb) > 2 { // payload has at least one field already
		out = append(out, ',')
	}
	out = append(out, xb[1:]...)
	return out, nil
}

// writeJSONResponse writes the JSON encoding of `payload`
// with the supplied status code and the `application/json`
// content-type header. Errors during encoding land in the
// logger but don't change the response status — the headers
// are already on the wire by then.
func writeJSONResponse(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(payload)
}

// writeJSONError writes an [ErrorEnvelope] response. Errors
// during encoding are silently dropped (the body has already
// started — there's nothing useful we can do).
func writeJSONError(w http.ResponseWriter, status int, code, message string) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(ErrorEnvelope{
		Error: true, Code: code, Message: message,
	})
}
