// ast.proto -- canonical AST shape produced by the clean-code
// service's AST adapter front end (architecture Sec 4.5,
// tech-spec Sec 4.5 / Sec 8.6) and consumed by every recipe in
// the foundation compute tier.
//
// Stage 2.1 of implementation-plan.md owns this file. The shape
// here is normative: every per-language parser implementation
// MUST produce a value of this type and every recipe MUST read
// only fields defined here. New per-language attributes ride on
// the open-ended `attrs` map rather than adding language-specific
// proto fields, so adding a v2 language (per Sec 8.6 v1 pin
// post-v1 extension model) does not require a proto schema bump.
//
// Versioning. Package is `clean_code.ast.v1`. A breaking change
// requires a new package name (`clean_code.ast.v2`) so two
// parser-fleet versions can co-exist during a rollout.
//
// Wire compatibility. Generated bindings are checked in at
// `internal/ast/v1/ast.pb.go`; running `make proto` regenerates
// them from this file. The check-in keeps `go build` / CI free
// of a hard `protoc` dependency.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ast/v1/ast.proto

package astv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScopeKind is the canonical scope discriminator pinned by
// architecture Sec 5.2.3 lines 1039-1050. Recipes MUST cite a
// `scope_kind` from this enum -- post-v1 additions (e.g. a new
// `lambda` kind) are a schema bump, not an in-place change.
type ScopeKind int32

const (
	// Default proto3 zero value; must be rejected by writers.
	ScopeKind_SCOPE_KIND_UNSPECIFIED ScopeKind = 0
	// Whole repository -- exactly one per `(repo_id, sha)`.
	ScopeKind_SCOPE_KIND_REPO ScopeKind = 1
	// Source package / directory grouping (Go package, Python
	// package, Java package, TypeScript folder module).
	ScopeKind_SCOPE_KIND_PACKAGE ScopeKind = 2
	// A single source file.
	ScopeKind_SCOPE_KIND_FILE ScopeKind = 3
	// A class declaration. For TypeScript also covers `class`
	// declarations; for Go this is unused (Go uses `interface`
	// for method-set polymorphism and struct types are flat).
	ScopeKind_SCOPE_KIND_CLASS ScopeKind = 4
	// An interface declaration (Go interface, Java interface,
	// TypeScript interface, Python ABC subclasses).
	ScopeKind_SCOPE_KIND_INTERFACE ScopeKind = 5
	// A method / function declaration.
	ScopeKind_SCOPE_KIND_METHOD ScopeKind = 6
	// A nested block within a method (the smallest scope kind).
	ScopeKind_SCOPE_KIND_BLOCK ScopeKind = 7
)

// Enum value maps for ScopeKind.
var (
	ScopeKind_name = map[int32]string{
		0: "SCOPE_KIND_UNSPECIFIED",
		1: "SCOPE_KIND_REPO",
		2: "SCOPE_KIND_PACKAGE",
		3: "SCOPE_KIND_FILE",
		4: "SCOPE_KIND_CLASS",
		5: "SCOPE_KIND_INTERFACE",
		6: "SCOPE_KIND_METHOD",
		7: "SCOPE_KIND_BLOCK",
	}
	ScopeKind_value = map[string]int32{
		"SCOPE_KIND_UNSPECIFIED": 0,
		"SCOPE_KIND_REPO":        1,
		"SCOPE_KIND_PACKAGE":     2,
		"SCOPE_KIND_FILE":        3,
		"SCOPE_KIND_CLASS":       4,
		"SCOPE_KIND_INTERFACE":   5,
		"SCOPE_KIND_METHOD":      6,
		"SCOPE_KIND_BLOCK":       7,
	}
)

func (x ScopeKind) Enum() *ScopeKind {
	p := new(ScopeKind)
	*p = x
	return p
}

func (x ScopeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScopeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ast_v1_ast_proto_enumTypes[0].Descriptor()
}

func (ScopeKind) Type() protoreflect.EnumType {
	return &file_ast_v1_ast_proto_enumTypes[0]
}

func (x ScopeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScopeKind.Descriptor instead.
func (ScopeKind) EnumDescriptor() ([]byte, []int) {
	return file_ast_v1_ast_proto_rawDescGZIP(), []int{0}
}

// AstRefKind discriminates whether an `AstRef.id` points at an
// `AstScope.scope_id` or an `AstSymbol.symbol_id`. Using a
// dedicated enum (rather than a oneof) keeps the wire shape
// stable for `AstEdge` endpoints when call-graph edges land
// (Stage 2.5 cycle / fan_in / fan_out recipes).
type AstRefKind int32

const (
	AstRefKind_AST_REF_KIND_UNSPECIFIED AstRefKind = 0
	AstRefKind_AST_REF_KIND_SCOPE       AstRefKind = 1
	AstRefKind_AST_REF_KIND_SYMBOL      AstRefKind = 2
)

// Enum value maps for AstRefKind.
var (
	AstRefKind_name = map[int32]string{
		0: "AST_REF_KIND_UNSPECIFIED",
		1: "AST_REF_KIND_SCOPE",
		2: "AST_REF_KIND_SYMBOL",
	}
	AstRefKind_value = map[string]int32{
		"AST_REF_KIND_UNSPECIFIED": 0,
		"AST_REF_KIND_SCOPE":       1,
		"AST_REF_KIND_SYMBOL":      2,
	}
)

func (x AstRefKind) Enum() *AstRefKind {
	p := new(AstRefKind)
	*p = x
	return p
}

func (x AstRefKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AstRefKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ast_v1_ast_proto_enumTypes[1].Descriptor()
}

func (AstRefKind) Type() protoreflect.EnumType {
	return &file_ast_v1_ast_proto_enumTypes[1]
}

func (x AstRefKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AstRefKind.Descriptor instead.
func (AstRefKind) EnumDescriptor() ([]byte, []int) {
	return file_ast_v1_ast_proto_rawDescGZIP(), []int{1}
}

// AstRange identifies a contiguous byte range in the source
// file. Lines and columns are 1-indexed (editor convention);
// bytes are 0-indexed (Go convention). Producers MUST populate
// all six fields so downstream rendering (Refactor Planner
// citation surface, Insights UI) never has to re-tokenise.
type AstRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartByte     uint32                 `protobuf:"varint,1,opt,name=start_byte,json=startByte,proto3" json:"start_byte,omitempty"`
	EndByte       uint32                 `protobuf:"varint,2,opt,name=end_byte,json=endByte,proto3" json:"end_byte,omitempty"`
	StartLine     uint32                 `protobuf:"varint,3,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       uint32                 `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	StartCol      uint32                 `protobuf:"varint,5,opt,name=start_col,json=startCol,proto3" json:"start_col,omitempty"`
	EndCol        uint32                 `protobuf:"varint,6,opt,name=end_col,json=endCol,proto3" json:"end_col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AstRange) Reset() {
	*x = AstRange{}
	mi := &file_ast_v1_ast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AstRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstRange) ProtoMessage() {}

func (x *AstRange) ProtoReflect() protoreflect.Message {
	mi := &file_ast_v1_ast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstRange.ProtoReflect.Descriptor instead.
func (*AstRange) Descriptor() ([]byte, []int) {
	return file_ast_v1_ast_proto_rawDescGZIP(), []int{0}
}

func (x *AstRange) GetStartByte() uint32 {
	if x != nil {
		return x.StartByte
	}
	return 0
}

func (x *AstRange) GetEndByte() uint32 {
	if x != nil {
		return x.EndByte
	}
	return 0
}

func (x *AstRange) GetStartLine() uint32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *AstRange) GetEndLine() uint32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *AstRange) GetStartCol() uint32 {
	if x != nil {
		return x.StartCol
	}
	return 0
}

func (x *AstRange) GetEndCol() uint32 {
	if x != nil {
		return x.EndCol
	}
	return 0
}

// AstRef is the polymorphic endpoint type used by `AstEdge`.
// `id` is either a `scope_id` or `symbol_id` depending on
// `kind`; consumers MUST switch on `kind` before treating `id`
// as one or the other.
type AstRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          AstRefKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=clean_code.ast.v1.AstRefKind" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AstRef) Reset() {
	*x = AstRef{}
	mi := &file_ast_v1_ast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AstRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstRef) ProtoMessage() {}

func (x *AstRef) ProtoReflect() protoreflect.Message {
	mi := &file_ast_v1_ast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstRef.ProtoReflect.Descriptor instead.
func (*AstRef) Descriptor() ([]byte, []int) {
	return file_ast_v1_ast_proto_rawDescGZIP(), []int{1}
}

func (x *AstRef) GetKind() AstRefKind {
	if x != nil {
		return x.Kind
	}
	return AstRefKind_AST_REF_KIND_UNSPECIFIED
}

func (x *AstRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// AstScope is a contiguous region of source code with a
// well-defined `scope_kind` and a canonical signature. Stage
// 2.1 (this stage) populates `scope_kind`, `name`,
// `qualified_name`, `parameters`, `range`, `parent_scope_id`,
// and `attrs`. Stage 2.2 mints `scope_id` and
// `canonical_signature` from those fields per architecture Sec
// 5.2.3 lines 1039-1050; Stage 2.1 leaves them empty.
type AstScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deterministic uuid derived from `(repo_id, scope_kind,
	// canonical_signature, first_seen_sha)`. Populated by Stage
	// 2.2's scope identity writer; Stage 2.1 parsers leave it
	// empty so the parser does not need a repo handle.
	ScopeId string `protobuf:"bytes,1,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	// Canonical discriminator (file/class/interface/method/...).
	ScopeKind ScopeKind `protobuf:"varint,2,opt,name=scope_kind,json=scopeKind,proto3,enum=clean_code.ast.v1.ScopeKind" json:"scope_kind,omitempty"`
	// Language-stable identifier (e.g. `pkg.Foo#bar(int)`).
	// Populated by Stage 2.2; Stage 2.1 leaves it empty.
	CanonicalSignature string `protobuf:"bytes,3,opt,name=canonical_signature,json=canonicalSignature,proto3" json:"canonical_signature,omitempty"`
	// Short, language-specific name (e.g. `Foo`, `bar`,
	// `__init__`). For files this is the basename; for packages
	// the last path segment.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Fully qualified, dot-separated path through enclosing
	// scopes (e.g. `pkg.Foo.bar`). Stage 2.2 builds
	// `canonical_signature` from this plus `parameters`.
	QualifiedName string `protobuf:"bytes,5,opt,name=qualified_name,json=qualifiedName,proto3" json:"qualified_name,omitempty"`
	// Parameter type list for method scopes; empty for other
	// scope kinds. Order matches the source declaration. Types
	// are the language's surface syntax (e.g. `int`, `string`,
	// `T`, `*Foo`).
	Parameters []string `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// Source range; required for every scope.
	Range *AstRange `protobuf:"bytes,7,opt,name=range,proto3" json:"range,omitempty"`
	// ID of the enclosing scope, if any (e.g. a method's parent
	// is its class; a class's parent is its file). The file
	// scope's parent is empty. Populated by parsers using a
	// stable intra-file ordinal (Stage 2.1) and rewritten by
	// Stage 2.2 to the durable `scope_id`.
	ParentScopeId string `protobuf:"bytes,8,opt,name=parent_scope_id,json=parentScopeId,proto3" json:"parent_scope_id,omitempty"`
	// Open-ended language-specific attributes (visibility,
	// return type, modifiers, generic parameters, ...). Insert-
	// time only -- once a `ScopeBinding` row is written by Stage
	// 2.2 the attrs are frozen.
	Attrs         map[string]string `protobuf:"bytes,9,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AstScope) Reset() {
	*x = AstScope{}
	mi := &file_ast_v1_ast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AstScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstScope) ProtoMessage() {}

func (x *AstScope) ProtoReflect() protoreflect.Message {
	mi := &file_ast_v1_ast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstScope.ProtoReflect.Descriptor instead.
func (*AstScope) Descriptor() ([]byte, []int) {
	return file_ast_v1_ast_proto_rawDescGZIP(), []int{2}
}

func (x *AstScope) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *AstScope) GetScopeKind() ScopeKind {
	if x != nil {
		return x.ScopeKind
	}
	return ScopeKind_SCOPE_KIND_UNSPECIFIED
}

func (x *AstScope) GetCanonicalSignature() string {
	if x != nil {
		return x.CanonicalSignature
	}
	return ""
}

func (x *AstScope) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AstScope) GetQualifiedName() string {
	if x != nil {
		return x.QualifiedName
	}
	return ""
}

func (x *AstScope) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *AstScope) GetRange() *AstRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *AstScope) GetParentScopeId() string {
	if x != nil {
		return x.ParentScopeId
	}
	return ""
}

func (x *AstScope) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

// AstSymbol is a named declaration inside a scope (a parameter,
// a local variable, an imported identifier, a struct field).
// Stage 2.1 emits the minimal set needed by recipes that read
// identifiers (e.g. `coupling_between_objects` for type
// references); richer symbol-table material can land in later
// stages without a schema bump.
type AstSymbol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable per-file identifier (intra-file ordinal). Stage 2.2
	// may rewrite to a durable cross-file id when symbols become
	// first-class scope-binding entries.
	SymbolId string `protobuf:"bytes,1,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Free-form symbol kind tag (`parameter`, `local`, `import`,
	// `field`). The kind set is intentionally open so a per-
	// language parser can introduce new categories without a
	// proto bump.
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// ID of the scope this symbol is declared in.
	ScopeId       string            `protobuf:"bytes,4,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Range         *AstRange         `protobuf:"bytes,5,opt,name=range,proto3" json:"range,omitempty"`
	Attrs         map[string]string `protobuf:"bytes,6,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AstSymbol) Reset() {
	*x = AstSymbol{}
	mi := &file_ast_v1_ast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AstSymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstSymbol) ProtoMessage() {}

func (x *AstSymbol) ProtoReflect() protoreflect.Message {
	mi := &file_ast_v1_ast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstSymbol.ProtoReflect.Descriptor instead.
func (*AstSymbol) Descriptor() ([]byte, []int) {
	return file_ast_v1_ast_proto_rawDescGZIP(), []int{3}
}

func (x *AstSymbol) GetSymbolId() string {
	if x != nil {
		return x.SymbolId
	}
	return ""
}

func (x *AstSymbol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AstSymbol) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AstSymbol) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *AstSymbol) GetRange() *AstRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *AstSymbol) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

// AstEdge connects two `AstRef`s (scope-scope, scope-symbol, or
// symbol-symbol). Used by Stage 2.5 fan_in / fan_out / cycle
// recipes (the `kind` field carries `calls`, `imports`,
// `extends`, `implements`, etc.).
type AstEdge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable per-file identifier (intra-file ordinal).
	EdgeId string `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	// Edge category (`calls`, `extends`, `implements`,
	// `imports`, `contains`, ...). Open enum -- per-language
	// parsers can introduce new categories without a proto bump.
	Kind          string            `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	From          *AstRef           `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            *AstRef           `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Attrs         map[string]string `protobuf:"bytes,5,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AstEdge) Reset() {
	*x = AstEdge{}
	mi := &file_ast_v1_ast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AstEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstEdge) ProtoMessage() {}

func (x *AstEdge) ProtoReflect() protoreflect.Message {
	mi := &file_ast_v1_ast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstEdge.ProtoReflect.Descriptor instead.
func (*AstEdge) Descriptor() ([]byte, []int) {
	return file_ast_v1_ast_proto_rawDescGZIP(), []int{4}
}

func (x *AstEdge) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *AstEdge) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AstEdge) GetFrom() *AstRef {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *AstEdge) GetTo() *AstRef {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *AstEdge) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

// AstFile is the output of one `Parser.Parse(ctx, path, bytes)`
// call -- a self-contained canonical AST for a single source
// file. Recipes ALWAYS read from `AstFile`; they never re-
// tokenise the original source.
type AstFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ISO-style language tag matching the parser registry key
	// (`go`, `python`, `typescript`, `java`). The
	// four v1-pinned values are normative; a fifth value is
	// rejected by the registry per tech-spec Sec 8.6.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Repo-relative path of the source file (forward-slash on
	// all platforms; producers MUST normalise `\` -> `/`).
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// SHA-256 of the input bytes, hex-encoded. Used by the
	// recipe layer to short-circuit when an unchanged file is
	// re-parsed (cache hit) -- the file bytes alone determine
	// the AST shape for a given parser version.
	ContentSha256 string `protobuf:"bytes,3,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	// Tree-sitter / grammar version pin used by the producer.
	// Mirrors `recipe_manifest.grammar_version` so a future
	// grammar upgrade lands as a new pinned version rather than
	// a silent re-parse (tech-spec Sec 9.14).
	ParserVersion string `protobuf:"bytes,4,opt,name=parser_version,json=parserVersion,proto3" json:"parser_version,omitempty"`
	// Scopes discovered in the file. Order is source order
	// (a stable DFS traversal of the parse tree).
	Scopes []*AstScope `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Symbols discovered in the file. Order is source order.
	Symbols []*AstSymbol `protobuf:"bytes,6,rep,name=symbols,proto3" json:"symbols,omitempty"`
	// Edges discovered in the file. Order is source order.
	Edges []*AstEdge `protobuf:"bytes,7,rep,name=edges,proto3" json:"edges,omitempty"`
	// Parse-time degraded reason (`tree_sitter_panic`,
	// `unknown_grammar`, `parse_truncated`, ...). Empty when the
	// parse was clean. Mirrors `MetricSample.degraded_reason`
	// (architecture Sec 5.2.1 lines 994-1003) so a degraded
	// parse can be carried forward into recipe output without
	// re-encoding the reason.
	DegradedReason string `protobuf:"bytes,8,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`
	// Open-ended per-file metadata (e.g. detected encoding,
	// shebang interpreter).
	Attrs         map[string]string `protobuf:"bytes,9,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AstFile) Reset() {
	*x = AstFile{}
	mi := &file_ast_v1_ast_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AstFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstFile) ProtoMessage() {}

func (x *AstFile) ProtoReflect() protoreflect.Message {
	mi := &file_ast_v1_ast_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstFile.ProtoReflect.Descriptor instead.
func (*AstFile) Descriptor() ([]byte, []int) {
	return file_ast_v1_ast_proto_rawDescGZIP(), []int{5}
}

func (x *AstFile) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AstFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AstFile) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *AstFile) GetParserVersion() string {
	if x != nil {
		return x.ParserVersion
	}
	return ""
}

func (x *AstFile) GetScopes() []*AstScope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *AstFile) GetSymbols() []*AstSymbol {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *AstFile) GetEdges() []*AstEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *AstFile) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

func (x *AstFile) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

var File_ast_v1_ast_proto protoreflect.FileDescriptor

const file_ast_v1_ast_proto_rawDesc = "" +
	"\n" +
	"\x10ast/v1/ast.proto\x12\x11clean_code.ast.v1\"\xb4\x01\n" +
	"\bAstRange\x12\x1d\n" +
	"\n" +
	"start_byte\x18\x01 \x01(\rR\tstartByte\x12\x19\n" +
	"\bend_byte\x18\x02 \x01(\rR\aendByte\x12\x1d\n" +
	"\n" +
	"start_line\x18\x03 \x01(\rR\tstartLine\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\rR\aendLine\x12\x1b\n" +
	"\tstart_col\x18\x05 \x01(\rR\bstartCol\x12\x17\n" +
	"\aend_col\x18\x06 \x01(\rR\x06endCol\"K\n" +
	"\x06AstRef\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1d.clean_code.ast.v1.AstRefKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xc1\x03\n" +
	"\bAstScope\x12\x19\n" +
	"\bscope_id\x18\x01 \x01(\tR\ascopeId\x12;\n" +
	"\n" +
	"scope_kind\x18\x02 \x01(\x0e2\x1c.clean_code.ast.v1.ScopeKindR\tscopeKind\x12/\n" +
	"\x13canonical_signature\x18\x03 \x01(\tR\x12canonicalSignature\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\x0equalified_name\x18\x05 \x01(\tR\rqualifiedName\x12\x1e\n" +
	"\n" +
	"parameters\x18\x06 \x03(\tR\n" +
	"parameters\x121\n" +
	"\x05range\x18\a \x01(\v2\x1b.clean_code.ast.v1.AstRangeR\x05range\x12&\n" +
	"\x0fparent_scope_id\x18\b \x01(\tR\rparentScopeId\x12<\n" +
	"\x05attrs\x18\t \x03(\v2&.clean_code.ast.v1.AstScope.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x02\n" +
	"\tAstSymbol\x12\x1b\n" +
	"\tsymbol_id\x18\x01 \x01(\tR\bsymbolId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x19\n" +
	"\bscope_id\x18\x04 \x01(\tR\ascopeId\x121\n" +
	"\x05range\x18\x05 \x01(\v2\x1b.clean_code.ast.v1.AstRangeR\x05range\x12=\n" +
	"\x05attrs\x18\x06 \x03(\v2'.clean_code.ast.v1.AstSymbol.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x02\n" +
	"\aAstEdge\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12-\n" +
	"\x04from\x18\x03 \x01(\v2\x19.clean_code.ast.v1.AstRefR\x04from\x12)\n" +
	"\x02to\x18\x04 \x01(\v2\x19.clean_code.ast.v1.AstRefR\x02to\x12;\n" +
	"\x05attrs\x18\x05 \x03(\v2%.clean_code.ast.v1.AstEdge.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x03\n" +
	"\aAstFile\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12%\n" +
	"\x0econtent_sha256\x18\x03 \x01(\tR\rcontentSha256\x12%\n" +
	"\x0eparser_version\x18\x04 \x01(\tR\rparserVersion\x123\n" +
	"\x06scopes\x18\x05 \x03(\v2\x1b.clean_code.ast.v1.AstScopeR\x06scopes\x126\n" +
	"\asymbols\x18\x06 \x03(\v2\x1c.clean_code.ast.v1.AstSymbolR\asymbols\x120\n" +
	"\x05edges\x18\a \x03(\v2\x1a.clean_code.ast.v1.AstEdgeR\x05edges\x12'\n" +
	"\x0fdegraded_reason\x18\b \x01(\tR\x0edegradedReason\x12;\n" +
	"\x05attrs\x18\t \x03(\v2%.clean_code.ast.v1.AstFile.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xc6\x01\n" +
	"\tScopeKind\x12\x1a\n" +
	"\x16SCOPE_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSCOPE_KIND_REPO\x10\x01\x12\x16\n" +
	"\x12SCOPE_KIND_PACKAGE\x10\x02\x12\x13\n" +
	"\x0fSCOPE_KIND_FILE\x10\x03\x12\x14\n" +
	"\x10SCOPE_KIND_CLASS\x10\x04\x12\x18\n" +
	"\x14SCOPE_KIND_INTERFACE\x10\x05\x12\x15\n" +
	"\x11SCOPE_KIND_METHOD\x10\x06\x12\x14\n" +
	"\x10SCOPE_KIND_BLOCK\x10\a*[\n" +
	"\n" +
	"AstRefKind\x12\x1c\n" +
	"\x18AST_REF_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12AST_REF_KIND_SCOPE\x10\x01\x12\x17\n" +
	"\x13AST_REF_KIND_SYMBOL\x10\x02BQZOforge/services/clean-code/internal/ast/v1;astv1b\x06proto3"

var (
	file_ast_v1_ast_proto_rawDescOnce sync.Once
	file_ast_v1_ast_proto_rawDescData []byte
)

func file_ast_v1_ast_proto_rawDescGZIP() []byte {
	file_ast_v1_ast_proto_rawDescOnce.Do(func() {
		file_ast_v1_ast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ast_v1_ast_proto_rawDesc), len(file_ast_v1_ast_proto_rawDesc)))
	})
	return file_ast_v1_ast_proto_rawDescData
}

var file_ast_v1_ast_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ast_v1_ast_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ast_v1_ast_proto_goTypes = []any{
	(ScopeKind)(0),    // 0: clean_code.ast.v1.ScopeKind
	(AstRefKind)(0),   // 1: clean_code.ast.v1.AstRefKind
	(*AstRange)(nil),  // 2: clean_code.ast.v1.AstRange
	(*AstRef)(nil),    // 3: clean_code.ast.v1.AstRef
	(*AstScope)(nil),  // 4: clean_code.ast.v1.AstScope
	(*AstSymbol)(nil), // 5: clean_code.ast.v1.AstSymbol
	(*AstEdge)(nil),   // 6: clean_code.ast.v1.AstEdge
	(*AstFile)(nil),   // 7: clean_code.ast.v1.AstFile
	nil,               // 8: clean_code.ast.v1.AstScope.AttrsEntry
	nil,               // 9: clean_code.ast.v1.AstSymbol.AttrsEntry
	nil,               // 10: clean_code.ast.v1.AstEdge.AttrsEntry
	nil,               // 11: clean_code.ast.v1.AstFile.AttrsEntry
}
var file_ast_v1_ast_proto_depIdxs = []int32{
	1,  // 0: clean_code.ast.v1.AstRef.kind:type_name -> clean_code.ast.v1.AstRefKind
	0,  // 1: clean_code.ast.v1.AstScope.scope_kind:type_name -> clean_code.ast.v1.ScopeKind
	2,  // 2: clean_code.ast.v1.AstScope.range:type_name -> clean_code.ast.v1.AstRange
	8,  // 3: clean_code.ast.v1.AstScope.attrs:type_name -> clean_code.ast.v1.AstScope.AttrsEntry
	2,  // 4: clean_code.ast.v1.AstSymbol.range:type_name -> clean_code.ast.v1.AstRange
	9,  // 5: clean_code.ast.v1.AstSymbol.attrs:type_name -> clean_code.ast.v1.AstSymbol.AttrsEntry
	3,  // 6: clean_code.ast.v1.AstEdge.from:type_name -> clean_code.ast.v1.AstRef
	3,  // 7: clean_code.ast.v1.AstEdge.to:type_name -> clean_code.ast.v1.AstRef
	10, // 8: clean_code.ast.v1.AstEdge.attrs:type_name -> clean_code.ast.v1.AstEdge.AttrsEntry
	4,  // 9: clean_code.ast.v1.AstFile.scopes:type_name -> clean_code.ast.v1.AstScope
	5,  // 10: clean_code.ast.v1.AstFile.symbols:type_name -> clean_code.ast.v1.AstSymbol
	6,  // 11: clean_code.ast.v1.AstFile.edges:type_name -> clean_code.ast.v1.AstEdge
	11, // 12: clean_code.ast.v1.AstFile.attrs:type_name -> clean_code.ast.v1.AstFile.AttrsEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ast_v1_ast_proto_init() }
func file_ast_v1_ast_proto_init() {
	if File_ast_v1_ast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ast_v1_ast_proto_rawDesc), len(file_ast_v1_ast_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ast_v1_ast_proto_goTypes,
		DependencyIndexes: file_ast_v1_ast_proto_depIdxs,
		EnumInfos:         file_ast_v1_ast_proto_enumTypes,
		MessageInfos:      file_ast_v1_ast_proto_msgTypes,
	}.Build()
	File_ast_v1_ast_proto = out.File
	file_ast_v1_ast_proto_goTypes = nil
	file_ast_v1_ast_proto_depIdxs = nil
}
