-- 0018_repo_webhook_secret.sql
--
-- Stage 3.5 step 2 (implementation-plan.md): persist the per-repo
-- HMAC secret used by the Webhook Receiver to authenticate
-- incoming push / merge payloads (risk §9.12). The secret is
-- generated by `mgmt.register` (Stage 7.1) once per repo and is
-- read by the Webhook Receiver on every inbound request.
--
-- Why a SEPARATE table, not a column on `repo`
-- --------------------------------------------
-- The `agent_memory_ro` reader role (migration 0017) holds
-- table-level SELECT on `repo`, AND 0017 installed an
-- `ALTER DEFAULT PRIVILEGES IN SCHEMA ... GRANT SELECT ON TABLES
-- TO agent_memory_ro` rule so every NEW table inherits SELECT
-- automatically. Putting the webhook secret on `repo` would
-- expose it to every recall / mgmt.read.* path; column-level
-- REVOKE works in principle but ages badly (every future column
-- added to `repo` would have to explicitly opt out). A separate
-- table whose default-privilege grant we REVOKE in this same
-- migration keeps the secret strictly behind the writer / admin
-- roles, where the Webhook Receiver (Stage 3.5) and
-- `mgmt.register` (Stage 7.1) live.
--
-- Cardinality
-- -----------
-- One row per repo (`repo_id` is PRIMARY KEY). `mgmt.register`
-- inserts on first onboarding; secret rotation (deferred per
-- tech-spec §9.12 residual risk) will UPDATE the row in place
-- and bump `rotated_at`.
--
-- Cascade semantics
-- -----------------
-- `ON DELETE CASCADE` on `repo_id` keeps the secret table in
-- sync if a repo is ever de-registered. Today `repo` is
-- `ON DELETE RESTRICT` from every other reference, so this
-- cascade only fires on a deliberate operator-level repo wipe.
--
-- Audit-log discipline
-- --------------------
-- The Webhook Receiver MUST NOT log `webhook_secret`, the
-- raw signature header, or the raw request body. This is a
-- code-level invariant (enforced in `internal/webhookreceiver`),
-- not a schema-level one.

-- migrate:up
BEGIN;

CREATE TABLE repo_webhook_secret (
    repo_id        uuid        PRIMARY KEY REFERENCES repo (repo_id) ON DELETE CASCADE,
    -- The HMAC pre-shared secret. Stored as text so the Webhook
    -- Receiver can hand the raw bytes straight to hmac.New(...).
    -- The secret is high-entropy (>= 32 bytes; Stage 7.1
    -- `mgmt.register` generates via crypto/rand) so no
    -- additional KDF is layered here.
    webhook_secret text        NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    -- rotated_at == created_at on first insert; bumped to now()
    -- on every secret rotation. Operators query
    -- `WHERE rotated_at < now() - interval '90 days'` to surface
    -- stale secrets per the §9.12 rotation runbook.
    rotated_at     timestamptz NOT NULL DEFAULT now()
);

-- agent_memory_app needs SELECT (Webhook Receiver lookup) and
-- INSERT + UPDATE (mgmt.register write + future rotation).
-- DELETE is intentionally withheld; secret de-registration
-- cascades through `ON DELETE CASCADE` on `repo` instead.
DO $$
DECLARE
    cs text := current_schema();
BEGIN
    EXECUTE format(
        'GRANT INSERT, SELECT, UPDATE ON %I.%I TO agent_memory_app',
        cs, 'repo_webhook_secret'
    );
END$$;

-- Revoke the SELECT grant that 0017's
--   `ALTER DEFAULT PRIVILEGES ... GRANT SELECT ON TABLES TO
--    agent_memory_ro`
-- installed for every new table in this schema. The reader role
-- MUST NOT see the secret -- recall / mgmt.read.* paths have no
-- business reading it. Two-step belt-and-braces:
--   1. REVOKE the SELECT that the default-privilege rule
--      auto-granted at CREATE TABLE time above.
--   2. REVOKE ALL just in case a future migration adds another
--      grant rule (e.g. INSERT default privileges).
DO $$
DECLARE
    cs text := current_schema();
BEGIN
    EXECUTE format(
        'REVOKE ALL PRIVILEGES ON %I.%I FROM agent_memory_ro',
        cs, 'repo_webhook_secret'
    );
END$$;

COMMIT;

-- migrate:down
BEGIN;

-- DROP TABLE cascades all ACL entries on this table. The
-- pg_default_acl rows installed by 0016 / 0017 are NOT touched
-- (they're per-schema, not per-table), so a round-trip leaves
-- the catalog byte-identical -- matching the contract that
-- `TestRoundTrip_schemaIsByteIdenticalAfterDownUp` asserts.
DROP TABLE IF EXISTS repo_webhook_secret;

COMMIT;
