-- 0018_repo_webhook_secret.sql
--
-- Stage 3.5 step 2 (implementation-plan.md): persist the per-repo
-- HMAC secret used by the Webhook Receiver to authenticate
-- incoming push / merge payloads (risk §9.12). The secret is
-- generated by `mgmt.register` (Stage 7.1) once per repo and is
-- read by the Webhook Receiver on every inbound request.
--
-- Why a SEPARATE table, not a column on `repo`
-- --------------------------------------------
-- The `agent_memory_ro` reader role (migration 0017) holds
-- table-level SELECT on `repo`, AND 0017 installed an
-- `ALTER DEFAULT PRIVILEGES IN SCHEMA ... GRANT SELECT ON TABLES
-- TO agent_memory_ro` rule so every NEW table inherits SELECT
-- automatically. Putting the webhook secret on `repo` would
-- expose it to every recall / mgmt.read.* path; column-level
-- REVOKE works in principle but ages badly (every future column
-- added to `repo` would have to explicitly opt out). A separate
-- table whose default-privilege grant we REVOKE in this same
-- migration keeps the secret strictly behind the writer / admin
-- roles, where the Webhook Receiver (Stage 3.5) and
-- `mgmt.register` (Stage 7.1) live.
--
-- Cardinality
-- -----------
-- One row per repo (`repo_id` is PRIMARY KEY). `mgmt.register`
-- inserts on first onboarding; secret rotation (deferred per
-- tech-spec §9.12 residual risk) will UPDATE the row in place
-- and bump `rotated_at`.
--
-- Cascade semantics
-- -----------------
-- `ON DELETE CASCADE` on `repo_id` keeps the secret table in
-- sync if a repo is ever de-registered. Today `repo` is
-- `ON DELETE RESTRICT` from every other reference, so this
-- cascade only fires on a deliberate operator-level repo wipe.
--
-- Audit-log discipline
-- --------------------
-- The Webhook Receiver MUST NOT log `webhook_secret`, the
-- raw signature header, or the raw request body. This is a
-- code-level invariant (enforced in `internal/webhookreceiver`),
-- not a schema-level one.
--
-- Residual risk -- cleartext storage at rest
-- ------------------------------------------
-- `webhook_secret` is stored as plain `text` in the table heap.
-- The ACLs defined below keep it invisible to `agent_memory_ro`
-- (recall / mgmt.read.* paths) at SQL level, but the ciphertext
-- of the heap pages is what ends up in:
--
--   * `pg_dump` / `pg_basebackup` artefacts,
--   * archived WAL segments and any standby's WAL stream,
--   * logical-replication subscribers if `repo_webhook_secret`
--     is ever added to a publication.
--
-- Anyone with read access to those byte streams can recover the
-- secret without ever touching a SQL connection. We accept this
-- residual risk in Stage 3.5 because the operational controls
-- below shift the trust boundary to the same operators who
-- already hold the schema-owner / superuser credentials -- a
-- strictly lower-privilege actor cannot reach the secret.
--
-- Required operational controls (deployment runbook MUST
-- enforce all of these; CI cannot verify them):
--
--   1. Backup encryption. `pg_dump` / `pg_basebackup` output is
--      written only to encrypted storage (Azure SSE with
--      customer-managed keys for the production cluster; GPG-
--      encrypted local archives for the dev stack).
--   2. WAL volume encryption. The pg_wal mount and any archive
--      target use storage-layer encryption (Azure disk encryption
--      / managed-disk SSE). Standbys replicate over TLS only.
--   3. Replication ACLs. If a logical-replication publication is
--      ever added to this database, `repo_webhook_secret` is
--      explicitly excluded from `FOR ALL TABLES` / table lists;
--      no external subscriber may consume the row stream.
--   4. Operator access. The schema-owner role (which can SELECT
--      this table regardless of the REVOKE below) is restricted
--      to the same operator tier that would hold a KMS key for
--      app-side encryption -- so adding `pgcrypto.pgp_sym_encrypt`
--      with a database-resident KEK would not raise the trust
--      bar, only the mechanical complexity.
--
-- Why we DO NOT use `pgcrypto.pgp_sym_encrypt(...)` today:
--
--   * Secret rotation itself is explicitly deferred to the
--     operations runbook per tech-spec §9.12. Envelope encryption
--     is only useful once a rotation story exists (the KEK has to
--     be rotatable, otherwise the ciphertext is just a more
--     awkward plaintext).
--   * No KMS integration is in scope for Stage 3.5. The
--     `pgcrypto` extension is loaded only for `gen_random_uuid()`
--     (tech-spec §8.7); introducing a key-wrap path here would
--     pull KMS access into the Webhook Receiver and
--     `mgmt.register` (Stage 7.1), both out of scope for this
--     stage.
--   * When rotation lands, the migration that adds rotation
--     tracking is the right place to convert this column to
--     `bytea` ciphertext via `pgp_sym_encrypt(secret,
--     current_setting('agent_memory.webhook_kek'))` and add a
--     `kek_version smallint` companion column. The TODO is
--     captured against §9.12 in the tech-spec.

-- migrate:up
BEGIN;

CREATE TABLE repo_webhook_secret (
    repo_id        uuid        PRIMARY KEY REFERENCES repo (repo_id) ON DELETE CASCADE,
    -- The HMAC pre-shared secret. Stored as text so the Webhook
    -- Receiver can hand the raw bytes straight to hmac.New(...).
    -- The secret is high-entropy (>= 32 bytes; Stage 7.1
    -- `mgmt.register` generates via crypto/rand) so no
    -- additional KDF is layered here.
    --
    -- Cleartext-at-rest residual risk is documented in the file
    -- header ("Residual risk -- cleartext storage at rest") and
    -- is mitigated by deployment-level controls (backup / WAL
    -- encryption, replication ACLs, operator-tier access) rather
    -- than app-side `pgcrypto` envelope encryption. App-side
    -- encryption is deferred to the same migration that lands
    -- the §9.12 secret-rotation story, which it depends on.
    webhook_secret text        NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    -- rotated_at == created_at on first insert; bumped to now()
    -- on every secret rotation. Operators query
    -- `WHERE rotated_at < now() - interval '90 days'` to surface
    -- stale secrets per the §9.12 rotation runbook.
    rotated_at     timestamptz NOT NULL DEFAULT now()
);

-- agent_memory_app needs SELECT (Webhook Receiver lookup) and
-- INSERT + UPDATE (mgmt.register write + future rotation).
-- DELETE is intentionally withheld; secret de-registration
-- cascades through `ON DELETE CASCADE` on `repo` instead.
DO $$
DECLARE
    cs text := current_schema();
BEGIN
    EXECUTE format(
        'GRANT INSERT, SELECT, UPDATE ON %I.%I TO agent_memory_app',
        cs, 'repo_webhook_secret'
    );
END$$;

-- Revoke the SELECT grant that 0017's
--   `ALTER DEFAULT PRIVILEGES ... GRANT SELECT ON TABLES TO
--    agent_memory_ro`
-- installed for every new table in this schema. The reader role
-- MUST NOT see the secret -- recall / mgmt.read.* paths have no
-- business reading it. Two-step belt-and-braces:
--   1. REVOKE the SELECT that the default-privilege rule
--      auto-granted at CREATE TABLE time above.
--   2. REVOKE ALL just in case a future migration adds another
--      grant rule (e.g. INSERT default privileges).
--
-- Note: this REVOKE is the SQL-level half of the cleartext-at-
-- rest mitigation. The deployment-level half (backup / WAL
-- encryption, replication ACLs) is enforced operationally per
-- the residual-risk section in this file's header.
DO $$
DECLARE
    cs text := current_schema();
BEGIN
    EXECUTE format(
        'REVOKE ALL PRIVILEGES ON %I.%I FROM agent_memory_ro',
        cs, 'repo_webhook_secret'
    );
END$$;

COMMIT;

-- migrate:down
BEGIN;

-- DROP TABLE cascades all ACL entries on this table. The
-- pg_default_acl rows installed by 0016 / 0017 are NOT touched
-- (they're per-schema, not per-table), so a round-trip leaves
-- the catalog byte-identical -- matching the contract that
-- `TestRoundTrip_schemaIsByteIdenticalAfterDownUp` asserts.
DROP TABLE IF EXISTS repo_webhook_secret;

COMMIT;
