// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Forge.Tests.Features.Code_Intelligence_CLEAN_CODE.Foundation_And_Schema
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ProjectScaffoldAndCIBaselineForClean_CodeServiceFeature
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "story-code-intelligence-CLEAN-CODE",
                "phase-foundation-and-schema",
                "stage-project-scaffold-and-ci-baseline",
                "setup-inline",
                "e2e"};
        
#line 1 "project-scaffold-and-ci-baseline.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, System.Threading.Thread.CurrentThread.ManagedThreadId.ToString());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/code-intelligence-CLEAN-CODE/foundation-and-schema", "Project scaffold and CI baseline for clean-code service", ("  As a platform engineer\r\n  I need the clean-code service scaffold to build, lint" +
                    ", and test cleanly\r\n  So that the CI pipeline guards code quality from the first" +
                    " commit"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Project scaffold and CI baseline for clean-code service")))
            {
                await global::Forge.Tests.Features.Code_Intelligence_CLEAN_CODE.Foundation_And_Schema.ProjectScaffoldAndCIBaselineForClean_CodeServiceFeature.FeatureSetupAsync(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 11
  #line hidden
#line 12
    await testRunner.GivenAsync("the code-intelligence repository root is known", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("scaffold-builds-clean")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Project scaffold and CI baseline for clean-code service")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("story-code-intelligence-CLEAN-CODE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("phase-foundation-and-schema")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("stage-project-scaffold-and-ci-baseline")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("setup-inline")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("e2e")]
        public async System.Threading.Tasks.Task Scaffold_Builds_Clean()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("scaffold-builds-clean", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 15
    await testRunner.GivenAsync("a fresh checkout", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
    await testRunner.WhenAsync("make build lint test runs in services/clean-code/", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.ThenAsync("it exits 0 with no missing-target errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 18
    await testRunner.AndAsync("it produces the clean-coded binary", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ci-workflow-triggers")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Project scaffold and CI baseline for clean-code service")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("story-code-intelligence-CLEAN-CODE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("phase-foundation-and-schema")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("stage-project-scaffold-and-ci-baseline")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("setup-inline")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("e2e")]
        public async System.Threading.Tasks.Task Ci_Workflow_Triggers()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ci-workflow-triggers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 21
    await testRunner.GivenAsync("a PR touching services/clean-code/**", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
    await testRunner.WhenAsync("GitHub Actions evaluates the workflow file", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
    await testRunner.ThenAsync((".github/workflows/clean-code-ci.yml runs make lint test and the container build j" +
                        "ob"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
    await testRunner.AndAsync("both succeed on the empty scaffold", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("config-honours-pins")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Project scaffold and CI baseline for clean-code service")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("story-code-intelligence-CLEAN-CODE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("phase-foundation-and-schema")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("stage-project-scaffold-and-ci-baseline")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("setup-inline")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("e2e")]
        public async System.Threading.Tasks.Task Config_Honours_Pins()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("config-honours-pins", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.GivenAsync("a config file that omits the five operator pins", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
    await testRunner.WhenAsync("the loader initialises", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("it returns defaults matching architecture Sec 1.6", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
    await testRunner.AndAsync("the default AST mode is embedded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync("the default coverage format is Cobertura XML", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("the default severity is warn", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.AndAsync("the default schema version is v1 required", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.AndAsync("the default model source is ML model from historical commits", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
