// agent.proto -- gRPC IDL for the Agent Surface (tech-spec §8.5).
//
// Stage 5.1 of implementation-plan.md ships the IDL for the
// `agent.recall` verb plus skeleton placeholders for the
// `agent.observe`, `agent.expand`, and `agent.summarize` verbs
// owned by Stages 5.2 / 5.3 / 5.4. Generated Go bindings will
// land alongside the protoc tooling pin in a follow-up; for
// now this file is the canonical contract that
// `cmd/agent-api/main.go` mTLS server speaks.
//
// Transport contract (tech-spec §8.5):
//   * gRPC over HTTP/2.
//   * Mutual TLS — the caller MUST present a client
//     certificate signed by the agent-memory CA. The server
//     refuses any connection that does not present a trusted
//     client cert.
//
// Recall envelope (architecture.md §6.1.1, e2e-scenarios.md §4):
//   * `context_id` is the durable RecallContextLog row id the
//     caller can later replay via `agent.observe(context_id=...)`.
//   * `nodes`, `edges`, `concepts` are score-ordered; the
//     reranker model version is pinned for reproducibility.
//   * `degraded` / `degraded_reason` surface §C22 closed-set
//     fallbacks; the recall response is NEVER hard-failed when
//     a degraded fallback is available — operators only see a
//     hard error when the verb itself is malformed.
//
// Versioning: this is `agent.v1`. Breaking changes require a
// new package name (`agent.v2`) so two server versions can
// run side-by-side during a rollout.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: proto/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Recall_FullMethodName    = "/agent.v1.AgentService/Recall"
	AgentService_Observe_FullMethodName   = "/agent.v1.AgentService/Observe"
	AgentService_Expand_FullMethodName    = "/agent.v1.AgentService/Expand"
	AgentService_Summarize_FullMethodName = "/agent.v1.AgentService/Summarize"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the Agent Surface mTLS endpoint
// (tech-spec §8.5). Each verb owns its own Stage in the
// implementation plan; Stage 5.1 is `Recall`.
type AgentServiceClient interface {
	// Recall is the §6.4 read path: embed the query, fan out a
	// mixed k-NN search across the Method / Block / Concept
	// Qdrant collections, filter out hits whose latest
	// EmbeddingPublishEvent is not `published`, expand the seed
	// set 1-2 structural hops through the GraphReader, rerank,
	// and durably append a RecallContextLog row before
	// returning.
	Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error)
	// Observe is the §6.1.2 agent outcome-record path. The
	// server validates the request (rejects
	// outcome=human_corrected and caller-supplied
	// observation_refs[].role=degraded_recall_context),
	// auto-stamps an extra
	// observation when the supplied context_id resolves to a
	// degraded recall row, transactionally appends one
	// Episode + N Observation rows to the EpisodicLog, and
	// returns the pre-minted episode_id (so the response is
	// deterministic even when the writer is later replayed
	// from the §7.5 WAL).
	Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error)
	// Expand walks structural edges from a node id; owned by
	// Stage 5.3. Placeholder.
	Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*ExpandResponse, error)
	// Summarize materialises a neighborhood card into a
	// natural-language summary; owned by Stage 5.4. Placeholder.
	Summarize(ctx context.Context, in *SummarizeRequest, opts ...grpc.CallOption) (*SummarizeResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallResponse)
	err := c.cc.Invoke(ctx, AgentService_Recall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveResponse)
	err := c.cc.Invoke(ctx, AgentService_Observe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (*ExpandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpandResponse)
	err := c.cc.Invoke(ctx, AgentService_Expand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Summarize(ctx context.Context, in *SummarizeRequest, opts ...grpc.CallOption) (*SummarizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeResponse)
	err := c.cc.Invoke(ctx, AgentService_Summarize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the Agent Surface mTLS endpoint
// (tech-spec §8.5). Each verb owns its own Stage in the
// implementation plan; Stage 5.1 is `Recall`.
type AgentServiceServer interface {
	// Recall is the §6.4 read path: embed the query, fan out a
	// mixed k-NN search across the Method / Block / Concept
	// Qdrant collections, filter out hits whose latest
	// EmbeddingPublishEvent is not `published`, expand the seed
	// set 1-2 structural hops through the GraphReader, rerank,
	// and durably append a RecallContextLog row before
	// returning.
	Recall(context.Context, *RecallRequest) (*RecallResponse, error)
	// Observe is the §6.1.2 agent outcome-record path. The
	// server validates the request (rejects
	// outcome=human_corrected and caller-supplied
	// observation_refs[].role=degraded_recall_context),
	// auto-stamps an extra
	// observation when the supplied context_id resolves to a
	// degraded recall row, transactionally appends one
	// Episode + N Observation rows to the EpisodicLog, and
	// returns the pre-minted episode_id (so the response is
	// deterministic even when the writer is later replayed
	// from the §7.5 WAL).
	Observe(context.Context, *ObserveRequest) (*ObserveResponse, error)
	// Expand walks structural edges from a node id; owned by
	// Stage 5.3. Placeholder.
	Expand(context.Context, *ExpandRequest) (*ExpandResponse, error)
	// Summarize materialises a neighborhood card into a
	// natural-language summary; owned by Stage 5.4. Placeholder.
	Summarize(context.Context, *SummarizeRequest) (*SummarizeResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Recall(context.Context, *RecallRequest) (*RecallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recall not implemented")
}
func (UnimplementedAgentServiceServer) Observe(context.Context, *ObserveRequest) (*ObserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedAgentServiceServer) Expand(context.Context, *ExpandRequest) (*ExpandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Expand not implemented")
}
func (UnimplementedAgentServiceServer) Summarize(context.Context, *SummarizeRequest) (*SummarizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Summarize not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Recall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Recall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Recall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Recall(ctx, req.(*RecallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Observe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Observe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Observe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Observe(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Expand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Expand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Expand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Expand(ctx, req.(*ExpandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Summarize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Summarize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Summarize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Summarize(ctx, req.(*SummarizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recall",
			Handler:    _AgentService_Recall_Handler,
		},
		{
			MethodName: "Observe",
			Handler:    _AgentService_Observe_Handler,
		},
		{
			MethodName: "Expand",
			Handler:    _AgentService_Expand_Handler,
		},
		{
			MethodName: "Summarize",
			Handler:    _AgentService_Summarize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent.proto",
}
