// agent.proto -- gRPC IDL for the Agent Surface (tech-spec §8.5).
//
// Stage 5.1 of implementation-plan.md ships the IDL for the
// `agent.recall` verb plus skeleton placeholders for the
// `agent.observe`, `agent.expand`, and `agent.summarize` verbs
// owned by Stages 5.2 / 5.3 / 5.4. Generated Go bindings will
// land alongside the protoc tooling pin in a follow-up; for
// now this file is the canonical contract that
// `cmd/agent-api/main.go` mTLS server speaks.
//
// Transport contract (tech-spec §8.5):
//   * gRPC over HTTP/2.
//   * Mutual TLS — the caller MUST present a client
//     certificate signed by the agent-memory CA. The server
//     refuses any connection that does not present a trusted
//     client cert.
//
// Recall envelope (architecture.md §6.1.1, e2e-scenarios.md §4):
//   * `context_id` is the durable RecallContextLog row id the
//     caller can later replay via `agent.observe(context_id=...)`.
//   * `nodes`, `edges`, `concepts` are score-ordered; the
//     reranker model version is pinned for reproducibility.
//   * `degraded` / `degraded_reason` surface §C22 closed-set
//     fallbacks; the recall response is NEVER hard-failed when
//     a degraded fallback is available — operators only see a
//     hard error when the verb itself is malformed.
//
// Versioning: this is `agent.v1`. Breaking changes require a
// new package name (`agent.v2`) so two server versions can
// run side-by-side during a rollout.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecallRequest is the input shape for `agent.recall`.
// Mirrors `internal/agentapi/recall.go.RecallRequest`.
type RecallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repo_id scopes the search to one repository (textual UUID).
	// Empty values fan out across all repos — discouraged in
	// production; the recall service logs a warning when set.
	RepoId string `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	// query is the natural-language string the agent wants to
	// ground its next step against. Empty queries are rejected
	// with INVALID_ARGUMENT.
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// k is the maximum number of ranked entries to return
	// (combined across nodes and concepts). Values <= 0 are
	// rejected; values above the per-call ceiling (256) are
	// coerced down server-side.
	K int32 `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`
	// kinds restricts the per-collection fan-out. The Stage
	// 5.1 mixed-seed contract (implementation-plan.md §7.8)
	// makes the production default the closed set
	// [method, block, concept] — when empty, the recall
	// service falls back to that union when concept fan-out
	// is enabled (the agent-api binary defaults it on; see
	// `AGENT_MEMORY_ENABLE_CONCEPTS`). Callers that want a
	// narrower view pass an explicit subset, e.g. ["method"]
	// for raw structural recall or ["concept"] to recall the
	// concept layer alone. Unknown kinds are rejected with
	// INVALID_ARGUMENT.
	Kinds         []string `protobuf:"bytes,4,rep,name=kinds,proto3" json:"kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RecallRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *RecallRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RecallRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *RecallRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

// NodeCard is the shape `agent.recall` returns for one Node
// hit (method or block). Mirrors `agentapi.Hit` augmented
// with the dereferenced canonical signature.
type NodeCard struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RepoId             string                 `protobuf:"bytes,2,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Kind               string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	CanonicalSignature string                 `protobuf:"bytes,4,opt,name=canonical_signature,json=canonicalSignature,proto3" json:"canonical_signature,omitempty"`
	// score is the reranker's final score for this entry;
	// descending across the response.
	Score float32 `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	// point_id is the Qdrant point id (textual UUID) used to
	// dereference the row through `embedding_publish`.
	PointId       string `protobuf:"bytes,6,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCard) Reset() {
	*x = NodeCard{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCard) ProtoMessage() {}

func (x *NodeCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCard.ProtoReflect.Descriptor instead.
func (*NodeCard) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *NodeCard) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeCard) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *NodeCard) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NodeCard) GetCanonicalSignature() string {
	if x != nil {
		return x.CanonicalSignature
	}
	return ""
}

func (x *NodeCard) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *NodeCard) GetPointId() string {
	if x != nil {
		return x.PointId
	}
	return ""
}

// EdgeCard is the shape for a structural edge surfaced via
// the GraphReader expansion. Stage 5.1 returns an empty
// `edges[]` when no expander is wired; the production
// composition root wires one.
type EdgeCard struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EdgeId    string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	RepoId    string                 `protobuf:"bytes,2,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Kind      string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	SrcNodeId string                 `protobuf:"bytes,4,opt,name=src_node_id,json=srcNodeId,proto3" json:"src_node_id,omitempty"`
	DstNodeId string                 `protobuf:"bytes,5,opt,name=dst_node_id,json=dstNodeId,proto3" json:"dst_node_id,omitempty"`
	// observation_count is the rolling TraceObservation
	// aggregate (§5.2.3); zero when the edge has no
	// observations OR when the agent-api binary has not been
	// wired with a TraceObservation counter (defence-in-depth
	// for environments where the Stage 4.2 span ingestor has
	// not yet populated the aggregate table). The production
	// composition root wires `sqlObservationCounter` so this
	// surfaces a real value.
	ObservationCount int64 `protobuf:"varint,6,opt,name=observation_count,json=observationCount,proto3" json:"observation_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EdgeCard) Reset() {
	*x = EdgeCard{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeCard) ProtoMessage() {}

func (x *EdgeCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeCard.ProtoReflect.Descriptor instead.
func (*EdgeCard) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *EdgeCard) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *EdgeCard) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *EdgeCard) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EdgeCard) GetSrcNodeId() string {
	if x != nil {
		return x.SrcNodeId
	}
	return ""
}

func (x *EdgeCard) GetDstNodeId() string {
	if x != nil {
		return x.DstNodeId
	}
	return ""
}

func (x *EdgeCard) GetObservationCount() int64 {
	if x != nil {
		return x.ObservationCount
	}
	return 0
}

// ConceptCard is the shape for a Concept hit (architecture
// §5.5.1). Stage 5.1 returns these when the Concept Promoter
// has published Concept embeddings to
// `agent_memory_concept`.
type ConceptCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConceptId     string                 `protobuf:"bytes,1,opt,name=concept_id,json=conceptId,proto3" json:"concept_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	PointId       string                 `protobuf:"bytes,4,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptCard) Reset() {
	*x = ConceptCard{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptCard) ProtoMessage() {}

func (x *ConceptCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptCard.ProtoReflect.Descriptor instead.
func (*ConceptCard) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ConceptCard) GetConceptId() string {
	if x != nil {
		return x.ConceptId
	}
	return ""
}

func (x *ConceptCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConceptCard) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ConceptCard) GetPointId() string {
	if x != nil {
		return x.PointId
	}
	return ""
}

// RecallResponse is the §6.1.1 envelope.
type RecallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// context_id is the durable RecallContextLog row id; the
	// caller stores this and can later replay the exact same
	// snapshot via `agent.observe(context_id=...)`.
	ContextId string `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// nodes / edges / concepts are score-ordered.
	Nodes    []*NodeCard    `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges    []*EdgeCard    `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	Concepts []*ConceptCard `protobuf:"bytes,4,rep,name=concepts,proto3" json:"concepts,omitempty"`
	// reranker_model_version pins the ranker that produced the
	// ordering. Mirrored verbatim onto the RecallContextLog row.
	RerankerModelVersion string `protobuf:"bytes,5,opt,name=reranker_model_version,json=rerankerModelVersion,proto3" json:"reranker_model_version,omitempty"`
	// degraded surfaces the §C22 closed-set fallback. When set,
	// degraded_reason is one of:
	//   - graph_store_unavailable
	//   - embedding_index_unavailable
	//   - reranker_model_stale
	//   - span_ingestor_backpressure
	//
	// The recall response is STILL served; the caller can
	// decide whether to retry or proceed with the snapshot.
	Degraded       bool   `protobuf:"varint,6,opt,name=degraded,proto3" json:"degraded,omitempty"`
	DegradedReason string `protobuf:"bytes,7,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`
	// over_fetched / filtered are observability fields the
	// operator dashboard uses to spot a publish backlog.
	OverFetched   int32 `protobuf:"varint,8,opt,name=over_fetched,json=overFetched,proto3" json:"over_fetched,omitempty"`
	Filtered      int32 `protobuf:"varint,9,opt,name=filtered,proto3" json:"filtered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallResponse) Reset() {
	*x = RecallResponse{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallResponse) ProtoMessage() {}

func (x *RecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallResponse.ProtoReflect.Descriptor instead.
func (*RecallResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RecallResponse) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *RecallResponse) GetNodes() []*NodeCard {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *RecallResponse) GetEdges() []*EdgeCard {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *RecallResponse) GetConcepts() []*ConceptCard {
	if x != nil {
		return x.Concepts
	}
	return nil
}

func (x *RecallResponse) GetRerankerModelVersion() string {
	if x != nil {
		return x.RerankerModelVersion
	}
	return ""
}

func (x *RecallResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *RecallResponse) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

func (x *RecallResponse) GetOverFetched() int32 {
	if x != nil {
		return x.OverFetched
	}
	return 0
}

func (x *RecallResponse) GetFiltered() int32 {
	if x != nil {
		return x.Filtered
	}
	return 0
}

// ObservationRef is one entry of `agent.observe.observation_refs[]`
// (architecture.md §6.1.2). Each ref maps onto exactly one
// `observation` row (§5.3.3). The caller MUST set the target
// field that matches the role (e.g. `role=node_hit` requires
// `node_id`); the server enforces the role/target pairing as
// part of validation and rejects the call with INVALID_ARGUMENT
// when the pairing is wrong.
//
// The `role` is one of the closed-set `observation_role` ENUM
// members EXCEPT `degraded_recall_context` — that role is
// reserved for the server-side auto-stamp path (§6.1.2). A
// caller-supplied `role=degraded_recall_context` is rejected
// with INVALID_ARGUMENT per C23.
type ObservationRef struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Role      string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	NodeId    string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EdgeId    string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	ConceptId string                 `protobuf:"bytes,4,opt,name=concept_id,json=conceptId,proto3" json:"concept_id,omitempty"`
	// weight is the caller-supplied "how much did this element
	// contribute to the action" measure (§5.3.3). Unbounded —
	// the schema does not pin a range — but the production
	// reranker treats it as a [0.0, 1.0] contribution and
	// operators expect that scale.
	Weight        float64 `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservationRef) Reset() {
	*x = ObservationRef{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationRef) ProtoMessage() {}

func (x *ObservationRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationRef.ProtoReflect.Descriptor instead.
func (*ObservationRef) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ObservationRef) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ObservationRef) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ObservationRef) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *ObservationRef) GetConceptId() string {
	if x != nil {
		return x.ConceptId
	}
	return ""
}

func (x *ObservationRef) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// ObserveRequest is the wire shape for `agent.observe`
// (architecture.md §6.1.2). The verb writes one `Episode`
// row plus one `Observation` row per `observation_refs[]`
// entry in a single transaction. See `internal/agentapi/observe.go`
// for the canonical Go contract.
//
// Closed-set rules:
//   - outcome MUST be one of {success, failure, refused,
//     degraded}. `human_corrected` is reserved for
//     `mgmt.feedback` (§6.2.2) — supplying it on observe is
//     rejected with INVALID_ARGUMENT per C15.
//   - observation_refs[*].role MUST be one of {node_hit,
//     edge_hit, call_edge_hit, concept_hit}. `degraded_recall_context`
//     is server-only per C23.
type ObserveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// context_id ties the Episode back to the recall snapshot
	// the agent consumed (architecture.md §6.1.2). REQUIRED for
	// `outcome != feedback` per the §5.3.1 schema CHECK.
	ContextId string `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// outcome is the closed-set `outcome` ENUM literal
	// (architecture.md §5.3.1). See the message-level closed-set
	// rules above for the rejection contract.
	Outcome string `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// actor is the legacy field carried over from the Stage 5.1
	// placeholder. The §6.1.2 schema does not name a separate
	// `actor` column on `Episode` — `kind='agent'` is always the
	// surrogate. Retained on the wire for backward-compat; the
	// server ignores it.
	Actor string `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	// repo_id (textual UUID) names the repo whose recall this
	// Episode is paired with. REQUIRED.
	RepoId string `protobuf:"bytes,4,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	// session_id is the agent's per-conversation correlation id
	// (free-form text). REQUIRED.
	SessionId string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// trace_id is the per-action trace correlation id (free-form
	// text). REQUIRED.
	TraceId string `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// action_json is the structured action the agent took, stored
	// verbatim on `Episode.action jsonb`. REQUIRED, MUST be valid
	// JSON.
	ActionJson []byte `protobuf:"bytes,7,opt,name=action_json,json=actionJson,proto3" json:"action_json,omitempty"`
	// signal_json is the optional reward / training signal the
	// agent surfaced (architecture.md §5.3.1). Stored verbatim on
	// `Episode.signal_json jsonb`. Empty or zero-length omits the
	// column.
	SignalJson []byte `protobuf:"bytes,8,opt,name=signal_json,json=signalJson,proto3" json:"signal_json,omitempty"`
	// observation_refs[] is the rank-ordered list of refs that
	// become `Observation` rows (one per ref). May be empty (an
	// Episode with no Observations is legal).
	ObservationRefs []*ObservationRef `protobuf:"bytes,9,rep,name=observation_refs,json=observationRefs,proto3" json:"observation_refs,omitempty"`
	// episode_group_id (textual UUID) is the optional group id
	// the agent uses to correlate a multi-step plan. When empty
	// the server mints a fresh group id.
	EpisodeGroupId string `protobuf:"bytes,10,opt,name=episode_group_id,json=episodeGroupId,proto3" json:"episode_group_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ObserveRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *ObserveRequest) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ObserveRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ObserveRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *ObserveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ObserveRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ObserveRequest) GetActionJson() []byte {
	if x != nil {
		return x.ActionJson
	}
	return nil
}

func (x *ObserveRequest) GetSignalJson() []byte {
	if x != nil {
		return x.SignalJson
	}
	return nil
}

func (x *ObserveRequest) GetObservationRefs() []*ObservationRef {
	if x != nil {
		return x.ObservationRefs
	}
	return nil
}

func (x *ObserveRequest) GetEpisodeGroupId() string {
	if x != nil {
		return x.EpisodeGroupId
	}
	return ""
}

// ObserveResponse is the wire shape for `agent.observe`.
// `episode_id` is durable across the WAL fallback: the
// pre-minted id surfaces on the response BEFORE the row is
// guaranteed to be in the partition, and the eventually-
// flushed `Episode` row carries the same id (architecture.md
// §7.5).
type ObserveResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	Degraded  bool                   `protobuf:"varint,2,opt,name=degraded,proto3" json:"degraded,omitempty"`
	// degraded_reason is one of the §C22 closed-set values:
	//   - episodic_log_unavailable  — Episode partition offline; WAL fallback engaged.
	//   - consolidator_backpressure — Episode written; Consolidator queue full.
	//
	// Empty when degraded=false.
	DegradedReason string `protobuf:"bytes,3,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`
	// episode_group_id echoes the resolved group id (server-
	// generated when the caller left the request field empty).
	EpisodeGroupId string `protobuf:"bytes,4,opt,name=episode_group_id,json=episodeGroupId,proto3" json:"episode_group_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ObserveResponse) Reset() {
	*x = ObserveResponse{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveResponse) ProtoMessage() {}

func (x *ObserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveResponse.ProtoReflect.Descriptor instead.
func (*ObserveResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ObserveResponse) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *ObserveResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *ObserveResponse) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

func (x *ObserveResponse) GetEpisodeGroupId() string {
	if x != nil {
		return x.EpisodeGroupId
	}
	return ""
}

type ExpandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Depth         int32                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ExpandRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExpandRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ExpandRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type ExpandResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Edges          []*EdgeCard            `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	ContextId      string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Degraded       bool                   `protobuf:"varint,3,opt,name=degraded,proto3" json:"degraded,omitempty"`
	DegradedReason string                 `protobuf:"bytes,4,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExpandResponse) Reset() {
	*x = ExpandResponse{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse) ProtoMessage() {}

func (x *ExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandResponse.ProtoReflect.Descriptor instead.
func (*ExpandResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ExpandResponse) GetEdges() []*EdgeCard {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ExpandResponse) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *ExpandResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *ExpandResponse) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

type SummarizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConceptId     string                 `protobuf:"bytes,2,opt,name=concept_id,json=conceptId,proto3" json:"concept_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *SummarizeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SummarizeRequest) GetConceptId() string {
	if x != nil {
		return x.ConceptId
	}
	return ""
}

type SummarizeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SummaryMd      string                 `protobuf:"bytes,1,opt,name=summary_md,json=summaryMd,proto3" json:"summary_md,omitempty"`
	ContextId      string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Degraded       bool                   `protobuf:"varint,3,opt,name=degraded,proto3" json:"degraded,omitempty"`
	DegradedReason string                 `protobuf:"bytes,4,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SummarizeResponse) Reset() {
	*x = SummarizeResponse{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeResponse) ProtoMessage() {}

func (x *SummarizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeResponse.ProtoReflect.Descriptor instead.
func (*SummarizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *SummarizeResponse) GetSummaryMd() string {
	if x != nil {
		return x.SummaryMd
	}
	return ""
}

func (x *SummarizeResponse) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *SummarizeResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *SummarizeResponse) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\bagent.v1\"b\n" +
	"\rRecallRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\f\n" +
	"\x01k\x18\x03 \x01(\x05R\x01k\x12\x14\n" +
	"\x05kinds\x18\x04 \x03(\tR\x05kinds\"\xb2\x01\n" +
	"\bNodeCard\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\arepo_id\x18\x02 \x01(\tR\x06repoId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12/\n" +
	"\x13canonical_signature\x18\x04 \x01(\tR\x12canonicalSignature\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\x12\x19\n" +
	"\bpoint_id\x18\x06 \x01(\tR\apointId\"\xbd\x01\n" +
	"\bEdgeCard\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x17\n" +
	"\arepo_id\x18\x02 \x01(\tR\x06repoId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1e\n" +
	"\vsrc_node_id\x18\x04 \x01(\tR\tsrcNodeId\x12\x1e\n" +
	"\vdst_node_id\x18\x05 \x01(\tR\tdstNodeId\x12+\n" +
	"\x11observation_count\x18\x06 \x01(\x03R\x10observationCount\"q\n" +
	"\vConceptCard\x12\x1d\n" +
	"\n" +
	"concept_id\x18\x01 \x01(\tR\tconceptId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12\x19\n" +
	"\bpoint_id\x18\x04 \x01(\tR\apointId\"\xf0\x02\n" +
	"\x0eRecallResponse\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12(\n" +
	"\x05nodes\x18\x02 \x03(\v2\x12.agent.v1.NodeCardR\x05nodes\x12(\n" +
	"\x05edges\x18\x03 \x03(\v2\x12.agent.v1.EdgeCardR\x05edges\x121\n" +
	"\bconcepts\x18\x04 \x03(\v2\x15.agent.v1.ConceptCardR\bconcepts\x124\n" +
	"\x16reranker_model_version\x18\x05 \x01(\tR\x14rerankerModelVersion\x12\x1a\n" +
	"\bdegraded\x18\x06 \x01(\bR\bdegraded\x12'\n" +
	"\x0fdegraded_reason\x18\a \x01(\tR\x0edegradedReason\x12!\n" +
	"\fover_fetched\x18\b \x01(\x05R\voverFetched\x12\x1a\n" +
	"\bfiltered\x18\t \x01(\x05R\bfiltered\"\x8d\x01\n" +
	"\x0eObservationRef\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\x12\x1d\n" +
	"\n" +
	"concept_id\x18\x04 \x01(\tR\tconceptId\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\"\xe3\x02\n" +
	"\x0eObserveRequest\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x17\n" +
	"\arepo_id\x18\x04 \x01(\tR\x06repoId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12\x1f\n" +
	"\vaction_json\x18\a \x01(\fR\n" +
	"actionJson\x12\x1f\n" +
	"\vsignal_json\x18\b \x01(\fR\n" +
	"signalJson\x12C\n" +
	"\x10observation_refs\x18\t \x03(\v2\x18.agent.v1.ObservationRefR\x0fobservationRefs\x12(\n" +
	"\x10episode_group_id\x18\n" +
	" \x01(\tR\x0eepisodeGroupId\"\x9f\x01\n" +
	"\x0fObserveResponse\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12\x1a\n" +
	"\bdegraded\x18\x02 \x01(\bR\bdegraded\x12'\n" +
	"\x0fdegraded_reason\x18\x03 \x01(\tR\x0edegradedReason\x12(\n" +
	"\x10episode_group_id\x18\x04 \x01(\tR\x0eepisodeGroupId\"\\\n" +
	"\rExpandRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\"\x9e\x01\n" +
	"\x0eExpandResponse\x12(\n" +
	"\x05edges\x18\x01 \x03(\v2\x12.agent.v1.EdgeCardR\x05edges\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12\x1a\n" +
	"\bdegraded\x18\x03 \x01(\bR\bdegraded\x12'\n" +
	"\x0fdegraded_reason\x18\x04 \x01(\tR\x0edegradedReason\"J\n" +
	"\x10SummarizeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"concept_id\x18\x02 \x01(\tR\tconceptId\"\x96\x01\n" +
	"\x11SummarizeResponse\x12\x1d\n" +
	"\n" +
	"summary_md\x18\x01 \x01(\tR\tsummaryMd\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12\x1a\n" +
	"\bdegraded\x18\x03 \x01(\bR\bdegraded\x12'\n" +
	"\x0fdegraded_reason\x18\x04 \x01(\tR\x0edegradedReason2\x8e\x02\n" +
	"\fAgentService\x12;\n" +
	"\x06Recall\x12\x17.agent.v1.RecallRequest\x1a\x18.agent.v1.RecallResponse\x12>\n" +
	"\aObserve\x12\x18.agent.v1.ObserveRequest\x1a\x19.agent.v1.ObserveResponse\x12;\n" +
	"\x06Expand\x12\x17.agent.v1.ExpandRequest\x1a\x18.agent.v1.ExpandResponse\x12D\n" +
	"\tSummarize\x12\x1a.agent.v1.SummarizeRequest\x1a\x1b.agent.v1.SummarizeResponseBQZOgithub.com/smartpcr/code-intelligence/services/agent-memory/proto/agent;agentpbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_agent_proto_goTypes = []any{
	(*RecallRequest)(nil),     // 0: agent.v1.RecallRequest
	(*NodeCard)(nil),          // 1: agent.v1.NodeCard
	(*EdgeCard)(nil),          // 2: agent.v1.EdgeCard
	(*ConceptCard)(nil),       // 3: agent.v1.ConceptCard
	(*RecallResponse)(nil),    // 4: agent.v1.RecallResponse
	(*ObservationRef)(nil),    // 5: agent.v1.ObservationRef
	(*ObserveRequest)(nil),    // 6: agent.v1.ObserveRequest
	(*ObserveResponse)(nil),   // 7: agent.v1.ObserveResponse
	(*ExpandRequest)(nil),     // 8: agent.v1.ExpandRequest
	(*ExpandResponse)(nil),    // 9: agent.v1.ExpandResponse
	(*SummarizeRequest)(nil),  // 10: agent.v1.SummarizeRequest
	(*SummarizeResponse)(nil), // 11: agent.v1.SummarizeResponse
}
var file_proto_agent_proto_depIdxs = []int32{
	1,  // 0: agent.v1.RecallResponse.nodes:type_name -> agent.v1.NodeCard
	2,  // 1: agent.v1.RecallResponse.edges:type_name -> agent.v1.EdgeCard
	3,  // 2: agent.v1.RecallResponse.concepts:type_name -> agent.v1.ConceptCard
	5,  // 3: agent.v1.ObserveRequest.observation_refs:type_name -> agent.v1.ObservationRef
	2,  // 4: agent.v1.ExpandResponse.edges:type_name -> agent.v1.EdgeCard
	0,  // 5: agent.v1.AgentService.Recall:input_type -> agent.v1.RecallRequest
	6,  // 6: agent.v1.AgentService.Observe:input_type -> agent.v1.ObserveRequest
	8,  // 7: agent.v1.AgentService.Expand:input_type -> agent.v1.ExpandRequest
	10, // 8: agent.v1.AgentService.Summarize:input_type -> agent.v1.SummarizeRequest
	4,  // 9: agent.v1.AgentService.Recall:output_type -> agent.v1.RecallResponse
	7,  // 10: agent.v1.AgentService.Observe:output_type -> agent.v1.ObserveResponse
	9,  // 11: agent.v1.AgentService.Expand:output_type -> agent.v1.ExpandResponse
	11, // 12: agent.v1.AgentService.Summarize:output_type -> agent.v1.SummarizeResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
